In [3]:
import torch
import numpy as np
import os
from torch import nn
import sys
import polars as pl
import sklearn
import shap
from functools import partial
import pandas as pd
import random
from matplotlib import pyplot as plt
import time
from rdkit.Chem import DataStructs
from tqdm import tqdm
from joblib import Parallel, delayed
import math
from skfp import fingerprints as skfps
from rdkit import Chem
from rdkit.Chem import AllChem

sys.path.append('../')
from src.utils.chem import normalize_smiles

In [4]:
train_df = pl.scan_csv('/home/dangnh36/datasets/competitions/leash_belka/processed/train_v2.csv').head(1000).select(
        pl.col('molecule'),
        pl.col('bb1', 'bb2', 'bb3').cast(pl.UInt16),
        pl.col('BRD4', 'HSA', 'sEH').cast(pl.UInt8),
    ).collect()
print(train_df.estimated_size('gb'), 'GB')
train_df

7.411371916532516e-05 GB


shape: (1_000, 7)
┌───────────────────────────────────┬──────┬──────┬──────┬──────┬─────┬─────┐
│ molecule                          ┆ bb1  ┆ bb2  ┆ bb3  ┆ BRD4 ┆ HSA ┆ sEH │
│ ---                               ┆ ---  ┆ ---  ┆ ---  ┆ ---  ┆ --- ┆ --- │
│ str                               ┆ u16  ┆ u16  ┆ u16  ┆ u8   ┆ u8  ┆ u8  │
╞═══════════════════════════════════╪══════╪══════╪══════╪══════╪═════╪═════╡
│ C#CCOc1ccc(CNc2nc(NCC3CCCN3c3ccc… ┆ 1640 ┆ 1653 ┆ 765  ┆ 0    ┆ 0   ┆ 0   │
│ C#CCOc1ccc(CNc2nc(NCc3cccc(Br)n3… ┆ 1640 ┆ 1653 ┆ 205  ┆ 0    ┆ 0   ┆ 0   │
│ C#CCOc1ccc(CNc2nc(NCc3ccc(OCC#C)… ┆ 1640 ┆ 1653 ┆ 1653 ┆ 0    ┆ 0   ┆ 0   │
│ C#CCOc1ccc(CNc2nc(NCCNC(=O)C(=C)… ┆ 1640 ┆ 1653 ┆ 146  ┆ 0    ┆ 0   ┆ 0   │
│ C#CCOc1ccc(CNc2nc(NCC(=O)NCC=C)n… ┆ 1640 ┆ 1653 ┆ 439  ┆ 0    ┆ 0   ┆ 0   │
│ …                                 ┆ …    ┆ …    ┆ …    ┆ …    ┆ …   ┆ …   │
│ C#CCOc1cccc(CNc2nc(NCc3cnn(Cc4cc… ┆ 1640 ┆ 1596 ┆ 585  ┆ 0    ┆ 0   ┆ 0   │
│ C#CCOc1cccc(CNc2nc(NCc3cnns3)nc(… ┆ 1640 ┆ 1596 ┆ 1813 ┆ 0    ┆ 0   ┆ 0   │
│ C#CCOc1cccc(CNc2nc(NCc3nc(-c4ccs… ┆ 1640 ┆ 1596 ┆ 1979 ┆ 0    ┆ 0   ┆ 0   │
│ C#CCOc1cccc(CNc2nc(NCc3nc4c(s3)C… ┆ 1640 ┆ 1596 ┆ 664  ┆ 0    ┆ 0   ┆ 0   │
│ C#CCOc1cccc(CNc2nc(NCc3nc4c(s3)C… ┆ 1640 ┆ 1596 ┆ 534  ┆ 0    ┆ 0   ┆ 0   │
└───────────────────────────────────┴──────┴──────┴──────┴──────┴─────┴─────┘

In [5]:
def create_3d_conformer_rdkit(mol, n = 1):
    new_mol = Chem.AddHs(mol)
    res = AllChem.EmbedMultipleConfs(new_mol, numConfs=n)
    ### MMFF generates multiple conformations
    res = AllChem.MMFFOptimizeMoleculeConfs(new_mol)
    new_mol = Chem.RemoveHs(new_mol)
    index = np.argmin([x[1] for x in res])
    energy = res[index][1]
    conf = new_mol.GetConformer(id=int(index))
    return conf

In [6]:
mols = [normalize_smiles(smiles,
                     canonical=True,
                     do_random = False,
                     isomeric=True,
                     kekulize = False,
                     replace_dy=True,
                     return_mol=True) for smiles in train_df[:, 'molecule']]
len(mols)

1000

In [19]:
%%time
for mol in tqdm(mols):
    xyz = create_3d_conformer_rdkit(mol).GetPositions()
    print(xyz.shape)

  0%|                                         | 1/1000 [00:00<11:38,  1.43it/s]

(41, 3)


  0%|                                         | 2/1000 [00:00<07:32,  2.20it/s]

(37, 3)


  0%|                                         | 3/1000 [00:01<08:32,  1.95it/s]

(40, 3)


  0%|▏                                        | 4/1000 [00:02<10:48,  1.54it/s]

(37, 3)


  0%|▏                                        | 5/1000 [00:02<08:19,  1.99it/s]

(36, 3)


  1%|▏                                        | 6/1000 [00:03<09:22,  1.77it/s]

(36, 3)


  1%|▎                                        | 7/1000 [00:03<07:43,  2.14it/s]

(36, 3)


  1%|▎                                        | 8/1000 [00:04<07:22,  2.24it/s]

(35, 3)


  1%|▎                                        | 9/1000 [00:05<10:21,  1.59it/s]

(47, 3)


  1%|▍                                       | 10/1000 [00:05<10:27,  1.58it/s]

(46, 3)


  1%|▍                                       | 11/1000 [00:05<08:31,  1.93it/s]

(38, 3)


  1%|▍                                       | 12/1000 [00:06<07:29,  2.20it/s]

(40, 3)


  1%|▌                                       | 13/1000 [00:06<07:33,  2.17it/s]

(39, 3)


  1%|▌                                       | 14/1000 [00:07<07:16,  2.26it/s]

(46, 3)


  2%|▌                                       | 15/1000 [00:07<06:33,  2.50it/s]

(38, 3)


  2%|▋                                       | 16/1000 [00:07<06:20,  2.58it/s]

(38, 3)


  2%|▋                                       | 17/1000 [00:08<05:39,  2.89it/s]

(36, 3)


  2%|▋                                       | 18/1000 [00:08<07:01,  2.33it/s]

(38, 3)


  2%|▊                                       | 19/1000 [00:09<08:00,  2.04it/s]

(37, 3)


  2%|▊                                       | 20/1000 [00:09<07:00,  2.33it/s]

(40, 3)


  2%|▊                                       | 21/1000 [00:09<06:46,  2.41it/s]

(35, 3)


  2%|▉                                       | 22/1000 [00:10<08:44,  1.86it/s]

(39, 3)


  2%|▉                                       | 23/1000 [00:11<08:29,  1.92it/s]

(40, 3)


  2%|▉                                       | 24/1000 [00:11<08:17,  1.96it/s]

(37, 3)


  2%|█                                       | 25/1000 [00:12<07:11,  2.26it/s]

(38, 3)


  3%|█                                       | 26/1000 [00:12<08:35,  1.89it/s]

(34, 3)


  3%|█                                       | 27/1000 [00:13<07:40,  2.12it/s]

(39, 3)


  3%|█                                       | 28/1000 [00:13<08:45,  1.85it/s]

(41, 3)


  3%|█▏                                      | 29/1000 [00:14<07:15,  2.23it/s]

(44, 3)


  3%|█▏                                      | 30/1000 [00:15<10:16,  1.57it/s]

(41, 3)


  3%|█▏                                      | 31/1000 [00:15<09:31,  1.70it/s]

(38, 3)


  3%|█▎                                      | 32/1000 [00:15<08:07,  1.99it/s]

(37, 3)


  3%|█▎                                      | 33/1000 [00:16<07:12,  2.24it/s]

(40, 3)


  3%|█▎                                      | 34/1000 [00:16<06:28,  2.49it/s]

(40, 3)


  4%|█▍                                      | 35/1000 [00:16<06:38,  2.42it/s]

(36, 3)


  4%|█▍                                      | 36/1000 [00:17<08:06,  1.98it/s]

(47, 3)


  4%|█▍                                      | 37/1000 [00:18<09:03,  1.77it/s]

(39, 3)


  4%|█▌                                      | 38/1000 [00:18<07:43,  2.08it/s]

(40, 3)


  4%|█▌                                      | 39/1000 [00:19<09:21,  1.71it/s]

(39, 3)


  4%|█▌                                      | 40/1000 [00:19<07:53,  2.03it/s]

(39, 3)


  4%|█▋                                      | 41/1000 [00:20<06:55,  2.31it/s]

(40, 3)


  4%|█▋                                      | 42/1000 [00:20<06:07,  2.61it/s]

(39, 3)


  4%|█▋                                      | 43/1000 [00:20<06:18,  2.53it/s]

(40, 3)


  4%|█▊                                      | 44/1000 [00:21<06:21,  2.51it/s]

(39, 3)


  4%|█▊                                      | 45/1000 [00:21<05:38,  2.82it/s]

(39, 3)


  5%|█▊                                      | 46/1000 [00:21<05:07,  3.10it/s]

(39, 3)


  5%|█▉                                      | 47/1000 [00:21<05:01,  3.16it/s]

(40, 3)


  5%|█▉                                      | 48/1000 [00:22<06:06,  2.60it/s]

(43, 3)


  5%|█▉                                      | 49/1000 [00:22<05:31,  2.87it/s]

(38, 3)


  5%|██                                      | 50/1000 [00:23<05:37,  2.81it/s]

(35, 3)


  5%|██                                      | 51/1000 [00:23<07:00,  2.26it/s]

(39, 3)


  5%|██                                      | 52/1000 [00:24<05:59,  2.63it/s]

(36, 3)


  5%|██                                      | 53/1000 [00:24<05:23,  2.92it/s]

(37, 3)


  5%|██▏                                     | 54/1000 [00:24<05:06,  3.09it/s]

(40, 3)


  6%|██▏                                     | 55/1000 [00:25<06:46,  2.33it/s]

(37, 3)


  6%|██▏                                     | 56/1000 [00:25<06:19,  2.49it/s]

(40, 3)


  6%|██▎                                     | 57/1000 [00:25<05:55,  2.65it/s]

(39, 3)


  6%|██▎                                     | 58/1000 [00:26<06:19,  2.48it/s]

(38, 3)


  6%|██▎                                     | 59/1000 [00:26<05:49,  2.70it/s]

(39, 3)


  6%|██▍                                     | 60/1000 [00:27<05:53,  2.66it/s]

(39, 3)


  6%|██▍                                     | 61/1000 [00:27<07:20,  2.13it/s]

(39, 3)


  6%|██▍                                     | 62/1000 [00:28<08:01,  1.95it/s]

(45, 3)


  6%|██▌                                     | 63/1000 [00:28<06:59,  2.23it/s]

(38, 3)


  6%|██▌                                     | 64/1000 [00:28<06:05,  2.56it/s]

(37, 3)


  6%|██▌                                     | 65/1000 [00:29<06:43,  2.32it/s]

(40, 3)


  7%|██▋                                     | 66/1000 [00:30<07:44,  2.01it/s]

(43, 3)


  7%|██▋                                     | 67/1000 [00:30<07:11,  2.16it/s]

(43, 3)


  7%|██▋                                     | 68/1000 [00:31<07:41,  2.02it/s]

(43, 3)


  7%|██▊                                     | 69/1000 [00:31<06:38,  2.34it/s]

(40, 3)


  7%|██▊                                     | 70/1000 [00:32<10:19,  1.50it/s]

(42, 3)


  7%|██▊                                     | 71/1000 [00:32<08:19,  1.86it/s]

(38, 3)


  7%|██▉                                     | 72/1000 [00:33<07:43,  2.00it/s]

(40, 3)


  7%|██▉                                     | 73/1000 [00:33<07:17,  2.12it/s]

(41, 3)


  7%|██▉                                     | 74/1000 [00:33<06:20,  2.43it/s]

(40, 3)


  8%|███                                     | 75/1000 [00:34<05:35,  2.76it/s]

(40, 3)


  8%|███                                     | 76/1000 [00:34<05:00,  3.07it/s]

(38, 3)


  8%|███                                     | 77/1000 [00:35<06:51,  2.24it/s]

(43, 3)


  8%|███                                     | 78/1000 [00:35<06:06,  2.52it/s]

(40, 3)


  8%|███▏                                    | 79/1000 [00:36<07:29,  2.05it/s]

(40, 3)


  8%|███▏                                    | 80/1000 [00:36<06:33,  2.34it/s]

(42, 3)


  8%|███▏                                    | 81/1000 [00:36<06:26,  2.38it/s]

(39, 3)


  8%|███▎                                    | 82/1000 [00:36<05:35,  2.74it/s]

(38, 3)


  8%|███▎                                    | 83/1000 [00:37<05:03,  3.02it/s]

(39, 3)


  8%|███▎                                    | 84/1000 [00:37<05:53,  2.59it/s]

(39, 3)


  8%|███▍                                    | 85/1000 [00:38<05:26,  2.80it/s]

(39, 3)


  9%|███▍                                    | 86/1000 [00:38<05:11,  2.94it/s]

(39, 3)


  9%|███▍                                    | 87/1000 [00:38<05:25,  2.80it/s]

(38, 3)


  9%|███▌                                    | 88/1000 [00:39<07:14,  2.10it/s]

(45, 3)


  9%|███▌                                    | 89/1000 [00:40<07:48,  1.94it/s]

(39, 3)


  9%|███▌                                    | 90/1000 [00:40<07:21,  2.06it/s]

(39, 3)


  9%|███▋                                    | 91/1000 [00:40<06:14,  2.43it/s]

(38, 3)


  9%|███▋                                    | 92/1000 [00:41<05:56,  2.55it/s]

(39, 3)


  9%|███▋                                    | 93/1000 [00:41<05:45,  2.62it/s]

(39, 3)


  9%|███▊                                    | 94/1000 [00:41<05:12,  2.90it/s]

(36, 3)


 10%|███▊                                    | 95/1000 [00:42<07:27,  2.02it/s]

(36, 3)


 10%|███▊                                    | 96/1000 [00:43<08:25,  1.79it/s]

(42, 3)


 10%|███▉                                    | 97/1000 [00:43<07:14,  2.08it/s]

(38, 3)


 10%|███▉                                    | 98/1000 [00:43<06:54,  2.18it/s]

(38, 3)


 10%|███▉                                    | 99/1000 [00:44<05:53,  2.55it/s]

(37, 3)


 10%|███▉                                   | 100/1000 [00:44<05:18,  2.83it/s]

(39, 3)


 10%|███▉                                   | 101/1000 [00:44<05:54,  2.54it/s]

(44, 3)


 10%|███▉                                   | 102/1000 [00:45<06:10,  2.42it/s]

(47, 3)


 10%|████                                   | 103/1000 [00:45<06:32,  2.29it/s]

(39, 3)


 10%|████                                   | 104/1000 [00:46<06:31,  2.29it/s]

(45, 3)


 10%|████                                   | 105/1000 [00:46<06:13,  2.39it/s]

(38, 3)


 11%|████▏                                  | 106/1000 [00:47<06:01,  2.47it/s]

(37, 3)


 11%|████▏                                  | 107/1000 [00:47<06:06,  2.44it/s]

(39, 3)


 11%|████▏                                  | 108/1000 [00:47<05:22,  2.76it/s]

(40, 3)


 11%|████▎                                  | 109/1000 [00:48<05:38,  2.63it/s]

(40, 3)


 11%|████▎                                  | 110/1000 [00:48<05:50,  2.54it/s]

(41, 3)


 11%|████▎                                  | 111/1000 [00:48<05:08,  2.88it/s]

(37, 3)


 11%|████▎                                  | 112/1000 [00:49<06:17,  2.35it/s]

(42, 3)


 11%|████▍                                  | 113/1000 [00:49<05:26,  2.72it/s]

(37, 3)


 11%|████▍                                  | 114/1000 [00:50<05:41,  2.59it/s]

(37, 3)


 12%|████▍                                  | 115/1000 [00:50<04:59,  2.95it/s]

(38, 3)


 12%|████▌                                  | 116/1000 [00:50<04:32,  3.25it/s]

(37, 3)


 12%|████▌                                  | 117/1000 [00:50<04:35,  3.20it/s]

(37, 3)


 12%|████▌                                  | 118/1000 [00:51<04:18,  3.41it/s]

(39, 3)


 12%|████▋                                  | 119/1000 [00:51<04:02,  3.63it/s]

(38, 3)


 12%|████▋                                  | 120/1000 [00:51<04:38,  3.16it/s]

(41, 3)


 12%|████▋                                  | 121/1000 [00:52<04:46,  3.07it/s]

(41, 3)


 12%|████▊                                  | 122/1000 [00:52<04:50,  3.02it/s]

(45, 3)


 12%|████▊                                  | 123/1000 [00:52<04:36,  3.18it/s]

(40, 3)


 12%|████▊                                  | 124/1000 [00:53<04:19,  3.38it/s]

(39, 3)


 12%|████▉                                  | 125/1000 [00:53<04:07,  3.54it/s]

(39, 3)


 13%|████▉                                  | 126/1000 [00:53<04:23,  3.32it/s]

(37, 3)


 13%|████▉                                  | 127/1000 [00:53<04:09,  3.50it/s]

(36, 3)


 13%|████▉                                  | 128/1000 [00:54<04:04,  3.56it/s]

(38, 3)


 13%|█████                                  | 129/1000 [00:54<04:06,  3.53it/s]

(34, 3)


 13%|█████                                  | 130/1000 [00:54<04:09,  3.49it/s]

(37, 3)


 13%|█████                                  | 131/1000 [00:55<04:25,  3.27it/s]

(41, 3)


 13%|█████▏                                 | 132/1000 [00:55<04:17,  3.37it/s]

(38, 3)


 13%|█████▏                                 | 133/1000 [00:55<04:00,  3.60it/s]

(37, 3)


 13%|█████▏                                 | 134/1000 [00:56<04:43,  3.05it/s]

(44, 3)


 14%|█████▎                                 | 135/1000 [00:56<05:09,  2.79it/s]

(41, 3)


 14%|█████▎                                 | 136/1000 [00:56<05:43,  2.51it/s]

(39, 3)


 14%|█████▎                                 | 137/1000 [00:57<06:37,  2.17it/s]

(37, 3)


 14%|█████▍                                 | 138/1000 [00:58<06:50,  2.10it/s]

(37, 3)


 14%|█████▍                                 | 139/1000 [00:58<06:11,  2.32it/s]

(37, 3)


 14%|█████▍                                 | 140/1000 [00:58<06:01,  2.38it/s]

(38, 3)


 14%|█████▍                                 | 141/1000 [00:59<05:44,  2.49it/s]

(46, 3)


 14%|█████▌                                 | 142/1000 [00:59<05:14,  2.72it/s]

(38, 3)


 14%|█████▌                                 | 143/1000 [00:59<06:11,  2.30it/s]

(37, 3)


 14%|█████▌                                 | 144/1000 [01:00<05:18,  2.68it/s]

(37, 3)


 14%|█████▋                                 | 145/1000 [01:00<04:41,  3.03it/s]

(37, 3)


 15%|█████▋                                 | 146/1000 [01:01<05:54,  2.41it/s]

(37, 3)


 15%|█████▋                                 | 147/1000 [01:01<05:23,  2.63it/s]

(37, 3)


 15%|█████▊                                 | 148/1000 [01:01<04:58,  2.85it/s]

(38, 3)


 15%|█████▊                                 | 149/1000 [01:02<06:25,  2.21it/s]

(35, 3)


 15%|█████▊                                 | 150/1000 [01:02<05:21,  2.65it/s]

(39, 3)


 15%|█████▉                                 | 151/1000 [01:02<05:11,  2.72it/s]

(36, 3)


 15%|█████▉                                 | 152/1000 [01:03<05:47,  2.44it/s]

(36, 3)


 15%|█████▉                                 | 153/1000 [01:03<05:43,  2.46it/s]

(37, 3)


 15%|██████                                 | 154/1000 [01:04<05:06,  2.76it/s]

(40, 3)


 16%|██████                                 | 155/1000 [01:04<05:43,  2.46it/s]

(40, 3)


 16%|██████                                 | 156/1000 [01:05<05:53,  2.39it/s]

(40, 3)


 16%|██████                                 | 157/1000 [01:05<07:46,  1.81it/s]

(38, 3)


 16%|██████▏                                | 158/1000 [01:07<10:12,  1.38it/s]

(38, 3)


 16%|██████▏                                | 159/1000 [01:07<08:24,  1.67it/s]

(38, 3)


 16%|██████▏                                | 160/1000 [01:07<08:29,  1.65it/s]

(43, 3)


 16%|██████▎                                | 161/1000 [01:08<07:37,  1.84it/s]

(37, 3)


 16%|██████▎                                | 162/1000 [01:08<06:27,  2.16it/s]

(38, 3)


 16%|██████▎                                | 163/1000 [01:08<06:04,  2.30it/s]

(37, 3)


 16%|██████▍                                | 164/1000 [01:09<05:52,  2.37it/s]

(38, 3)


 16%|██████▍                                | 165/1000 [01:09<05:03,  2.76it/s]

(36, 3)


 17%|██████▍                                | 166/1000 [01:10<05:18,  2.62it/s]

(40, 3)


 17%|██████▌                                | 167/1000 [01:10<05:17,  2.62it/s]

(39, 3)


 17%|██████▌                                | 168/1000 [01:10<04:54,  2.82it/s]

(39, 3)


 17%|██████▌                                | 169/1000 [01:11<04:57,  2.79it/s]

(37, 3)


 17%|██████▋                                | 170/1000 [01:11<04:42,  2.94it/s]

(41, 3)


 17%|██████▋                                | 171/1000 [01:11<04:25,  3.12it/s]

(39, 3)


 17%|██████▋                                | 172/1000 [01:12<04:51,  2.84it/s]

(36, 3)


 17%|██████▋                                | 173/1000 [01:12<04:27,  3.09it/s]

(36, 3)


 17%|██████▊                                | 174/1000 [01:12<05:11,  2.66it/s]

(45, 3)


 18%|██████▊                                | 175/1000 [01:13<04:40,  2.94it/s]

(36, 3)


 18%|██████▊                                | 176/1000 [01:13<04:29,  3.06it/s]

(36, 3)


 18%|██████▉                                | 177/1000 [01:13<04:52,  2.81it/s]

(38, 3)


 18%|██████▉                                | 178/1000 [01:14<05:58,  2.29it/s]

(35, 3)


 18%|██████▉                                | 179/1000 [01:14<05:08,  2.66it/s]

(37, 3)


 18%|███████                                | 180/1000 [01:15<05:10,  2.64it/s]

(36, 3)


 18%|███████                                | 181/1000 [01:15<04:30,  3.03it/s]

(35, 3)


 18%|███████                                | 182/1000 [01:15<04:07,  3.30it/s]

(36, 3)


 18%|███████▏                               | 183/1000 [01:15<04:07,  3.30it/s]

(36, 3)


 18%|███████▏                               | 184/1000 [01:16<04:10,  3.25it/s]

(38, 3)


 18%|███████▏                               | 185/1000 [01:16<05:47,  2.35it/s]

(40, 3)


 19%|███████▎                               | 186/1000 [01:17<05:05,  2.66it/s]

(37, 3)


 19%|███████▎                               | 187/1000 [01:17<05:06,  2.65it/s]

(37, 3)


 19%|███████▎                               | 188/1000 [01:17<05:24,  2.50it/s]

(38, 3)


 19%|███████▎                               | 189/1000 [01:18<05:04,  2.66it/s]

(37, 3)


 19%|███████▍                               | 190/1000 [01:18<05:08,  2.62it/s]

(41, 3)


 19%|███████▍                               | 191/1000 [01:18<04:50,  2.79it/s]

(39, 3)


 19%|███████▍                               | 192/1000 [01:19<04:40,  2.88it/s]

(35, 3)


 19%|███████▌                               | 193/1000 [01:19<04:07,  3.26it/s]

(35, 3)


 19%|███████▌                               | 194/1000 [01:19<03:56,  3.41it/s]

(38, 3)


 20%|███████▌                               | 195/1000 [01:20<05:11,  2.58it/s]

(36, 3)


 20%|███████▋                               | 196/1000 [01:20<04:43,  2.83it/s]

(39, 3)


 20%|███████▋                               | 197/1000 [01:22<10:49,  1.24it/s]

(48, 3)


 20%|███████▋                               | 198/1000 [01:22<08:29,  1.57it/s]

(36, 3)


 20%|███████▊                               | 199/1000 [01:23<08:00,  1.67it/s]

(38, 3)


 20%|███████▊                               | 200/1000 [01:24<10:46,  1.24it/s]

(41, 3)


 20%|███████▊                               | 201/1000 [01:24<09:09,  1.45it/s]

(38, 3)


 20%|███████▉                               | 202/1000 [01:25<08:05,  1.64it/s]

(42, 3)


 20%|███████▉                               | 203/1000 [01:25<07:09,  1.85it/s]

(39, 3)


 20%|███████▉                               | 204/1000 [01:26<06:12,  2.14it/s]

(40, 3)


 20%|███████▉                               | 205/1000 [01:26<05:32,  2.39it/s]

(39, 3)


 21%|████████                               | 206/1000 [01:26<05:02,  2.63it/s]

(40, 3)


 21%|████████                               | 207/1000 [01:26<04:32,  2.91it/s]

(39, 3)


 21%|████████                               | 208/1000 [01:27<04:15,  3.10it/s]

(41, 3)


 21%|████████▏                              | 209/1000 [01:27<04:09,  3.16it/s]

(39, 3)


 21%|████████▏                              | 210/1000 [01:27<03:54,  3.36it/s]

(38, 3)


 21%|████████▏                              | 211/1000 [01:27<03:53,  3.38it/s]

(37, 3)


 21%|████████▎                              | 212/1000 [01:28<03:54,  3.36it/s]

(41, 3)


 21%|████████▎                              | 213/1000 [01:28<03:49,  3.43it/s]

(40, 3)


 21%|████████▎                              | 214/1000 [01:28<03:43,  3.51it/s]

(39, 3)


 22%|████████▍                              | 215/1000 [01:29<03:35,  3.65it/s]

(40, 3)


 22%|████████▍                              | 216/1000 [01:29<05:18,  2.46it/s]

(41, 3)


 22%|████████▍                              | 217/1000 [01:30<04:48,  2.71it/s]

(38, 3)


 22%|████████▌                              | 218/1000 [01:30<04:33,  2.86it/s]

(37, 3)


 22%|████████▌                              | 220/1000 [01:31<04:48,  2.70it/s]

(41, 3)
(37, 3)


 22%|████████▌                              | 221/1000 [01:31<05:18,  2.44it/s]

(37, 3)


 22%|████████▋                              | 222/1000 [01:32<04:43,  2.75it/s]

(36, 3)


 22%|████████▋                              | 223/1000 [01:32<04:18,  3.01it/s]

(37, 3)


 22%|████████▋                              | 224/1000 [01:32<04:17,  3.01it/s]

(36, 3)


 22%|████████▊                              | 225/1000 [01:33<05:07,  2.52it/s]

(36, 3)


 23%|████████▊                              | 226/1000 [01:34<08:36,  1.50it/s]

(42, 3)


 23%|████████▊                              | 227/1000 [01:34<07:22,  1.75it/s]

(41, 3)


 23%|████████▉                              | 228/1000 [01:35<09:36,  1.34it/s]

(40, 3)


 23%|████████▉                              | 229/1000 [01:36<08:37,  1.49it/s]

(35, 3)


 23%|████████▉                              | 230/1000 [01:36<07:30,  1.71it/s]

(43, 3)


 23%|█████████                              | 231/1000 [01:37<06:47,  1.89it/s]

(38, 3)


 23%|█████████                              | 232/1000 [01:37<05:50,  2.19it/s]

(38, 3)


 23%|█████████                              | 233/1000 [01:37<05:04,  2.52it/s]

(35, 3)


 23%|█████████▏                             | 234/1000 [01:38<04:52,  2.62it/s]

(40, 3)


 24%|█████████▏                             | 235/1000 [01:38<04:58,  2.57it/s]

(36, 3)


 24%|█████████▏                             | 236/1000 [01:38<04:53,  2.61it/s]

(40, 3)


 24%|█████████▏                             | 237/1000 [01:39<04:36,  2.76it/s]

(41, 3)


 24%|█████████▎                             | 238/1000 [01:39<04:53,  2.60it/s]

(39, 3)


 24%|█████████▎                             | 239/1000 [01:40<05:17,  2.39it/s]

(41, 3)


 24%|█████████▎                             | 240/1000 [01:40<05:35,  2.27it/s]

(49, 3)


 24%|█████████▍                             | 241/1000 [01:41<05:48,  2.18it/s]

(39, 3)


 24%|█████████▍                             | 242/1000 [01:41<05:22,  2.35it/s]

(42, 3)


 24%|█████████▍                             | 243/1000 [01:41<04:54,  2.57it/s]

(41, 3)


 24%|█████████▌                             | 244/1000 [01:42<04:26,  2.84it/s]

(35, 3)


 24%|█████████▌                             | 245/1000 [01:42<05:33,  2.26it/s]

(39, 3)


 25%|█████████▌                             | 246/1000 [01:42<04:43,  2.66it/s]

(36, 3)


 25%|█████████▋                             | 247/1000 [01:43<05:28,  2.29it/s]

(40, 3)


 25%|█████████▋                             | 248/1000 [01:43<04:58,  2.52it/s]

(40, 3)


 25%|█████████▋                             | 249/1000 [01:44<04:35,  2.72it/s]

(41, 3)


 25%|█████████▊                             | 250/1000 [01:44<04:17,  2.91it/s]

(36, 3)


 25%|█████████▊                             | 251/1000 [01:44<04:03,  3.08it/s]

(41, 3)


 25%|█████████▊                             | 252/1000 [01:45<04:17,  2.91it/s]

(43, 3)


 25%|█████████▊                             | 253/1000 [01:46<09:34,  1.30it/s]

(38, 3)


 25%|█████████▉                             | 254/1000 [01:47<07:55,  1.57it/s]

(39, 3)


 26%|█████████▉                             | 255/1000 [01:47<06:42,  1.85it/s]

(41, 3)


 26%|█████████▉                             | 256/1000 [01:47<05:28,  2.26it/s]

(36, 3)


 26%|██████████                             | 257/1000 [01:47<04:40,  2.65it/s]

(39, 3)


 26%|██████████                             | 258/1000 [01:48<04:19,  2.86it/s]

(41, 3)


 26%|██████████▏                            | 260/1000 [01:48<03:32,  3.49it/s]

(41, 3)
(37, 3)


 26%|██████████▏                            | 261/1000 [01:49<04:48,  2.56it/s]

(39, 3)


 26%|██████████▏                            | 262/1000 [01:49<05:09,  2.38it/s]

(39, 3)


 26%|██████████▎                            | 263/1000 [01:50<04:23,  2.80it/s]

(36, 3)


 26%|██████████▎                            | 264/1000 [01:50<05:51,  2.10it/s]

(39, 3)


 26%|██████████▎                            | 265/1000 [01:51<06:08,  1.99it/s]

(40, 3)


 27%|██████████▎                            | 266/1000 [01:51<06:16,  1.95it/s]

(40, 3)


 27%|██████████▍                            | 267/1000 [01:52<05:21,  2.28it/s]

(41, 3)


 27%|██████████▍                            | 268/1000 [01:52<04:31,  2.70it/s]

(35, 3)


 27%|██████████▍                            | 269/1000 [01:52<04:38,  2.63it/s]

(40, 3)


 27%|██████████▌                            | 270/1000 [01:52<04:06,  2.96it/s]

(39, 3)


 27%|██████████▌                            | 271/1000 [01:53<04:35,  2.65it/s]

(40, 3)


 27%|██████████▌                            | 272/1000 [01:53<04:01,  3.02it/s]

(36, 3)


 27%|██████████▋                            | 273/1000 [01:54<04:02,  3.00it/s]

(45, 3)


 27%|██████████▋                            | 274/1000 [01:54<04:12,  2.87it/s]

(38, 3)


 28%|██████████▋                            | 275/1000 [01:54<03:54,  3.09it/s]

(39, 3)


 28%|██████████▊                            | 276/1000 [01:54<03:55,  3.07it/s]

(42, 3)


 28%|██████████▊                            | 277/1000 [01:55<05:58,  2.02it/s]

(39, 3)


 28%|██████████▊                            | 278/1000 [01:56<05:46,  2.08it/s]

(41, 3)


 28%|██████████▉                            | 279/1000 [01:56<05:26,  2.21it/s]

(36, 3)


 28%|██████████▉                            | 280/1000 [01:56<04:33,  2.63it/s]

(35, 3)


 28%|██████████▉                            | 281/1000 [01:57<04:18,  2.78it/s]

(35, 3)


 28%|██████████▉                            | 282/1000 [01:57<05:34,  2.14it/s]

(41, 3)


 28%|███████████                            | 283/1000 [01:58<04:42,  2.54it/s]

(37, 3)


 28%|███████████                            | 284/1000 [01:58<04:16,  2.79it/s]

(39, 3)


 28%|███████████                            | 285/1000 [01:58<04:30,  2.65it/s]

(36, 3)


 29%|███████████▏                           | 286/1000 [01:59<04:19,  2.75it/s]

(35, 3)


 29%|███████████▏                           | 288/1000 [01:59<03:38,  3.26it/s]

(41, 3)
(35, 3)


 29%|███████████▎                           | 289/1000 [02:00<03:35,  3.30it/s]

(36, 3)


 29%|███████████▎                           | 291/1000 [02:00<03:34,  3.31it/s]

(40, 3)
(36, 3)


 29%|███████████▍                           | 292/1000 [02:01<03:42,  3.19it/s]

(37, 3)


 29%|███████████▍                           | 293/1000 [02:01<03:30,  3.36it/s]

(41, 3)


 29%|███████████▍                           | 294/1000 [02:01<03:19,  3.54it/s]

(40, 3)


 30%|███████████▌                           | 295/1000 [02:01<03:02,  3.86it/s]

(37, 3)


 30%|███████████▌                           | 296/1000 [02:02<03:11,  3.68it/s]

(37, 3)


 30%|███████████▌                           | 297/1000 [02:02<02:58,  3.94it/s]

(36, 3)


 30%|███████████▌                           | 298/1000 [02:02<02:55,  3.99it/s]

(42, 3)


 30%|███████████▋                           | 299/1000 [02:02<02:46,  4.20it/s]

(37, 3)


 30%|███████████▋                           | 300/1000 [02:03<04:26,  2.63it/s]

(42, 3)


 30%|███████████▋                           | 301/1000 [02:03<05:08,  2.26it/s]

(36, 3)


 30%|███████████▊                           | 302/1000 [02:04<05:07,  2.27it/s]

(33, 3)


 30%|███████████▊                           | 303/1000 [02:04<05:01,  2.31it/s]

(42, 3)


 30%|███████████▊                           | 304/1000 [02:05<05:25,  2.14it/s]

(38, 3)


 30%|███████████▉                           | 305/1000 [02:05<05:41,  2.03it/s]

(44, 3)


 31%|███████████▉                           | 306/1000 [02:06<06:57,  1.66it/s]

(42, 3)


 31%|███████████▉                           | 307/1000 [02:07<06:28,  1.79it/s]

(38, 3)


 31%|████████████                           | 308/1000 [02:08<07:24,  1.56it/s]

(37, 3)


 31%|████████████                           | 309/1000 [02:08<07:31,  1.53it/s]

(40, 3)


 31%|████████████                           | 310/1000 [02:09<06:24,  1.79it/s]

(34, 3)


 31%|████████████▏                          | 311/1000 [02:10<10:43,  1.07it/s]

(43, 3)


 31%|████████████▏                          | 312/1000 [02:11<10:19,  1.11it/s]

(45, 3)


 31%|████████████▏                          | 313/1000 [02:12<08:37,  1.33it/s]

(38, 3)


 31%|████████████▏                          | 314/1000 [02:12<08:18,  1.38it/s]

(37, 3)


 32%|████████████▎                          | 315/1000 [02:13<08:11,  1.39it/s]

(37, 3)


 32%|████████████▎                          | 316/1000 [02:15<11:04,  1.03it/s]

(39, 3)


 32%|████████████▎                          | 317/1000 [02:15<09:30,  1.20it/s]

(42, 3)


 32%|████████████▍                          | 318/1000 [02:15<08:01,  1.42it/s]

(38, 3)


 32%|████████████▍                          | 319/1000 [02:16<07:00,  1.62it/s]

(41, 3)


 32%|████████████▍                          | 320/1000 [02:17<07:22,  1.54it/s]

(43, 3)


 32%|████████████▌                          | 321/1000 [02:17<06:41,  1.69it/s]

(41, 3)


 32%|████████████▌                          | 322/1000 [02:18<06:59,  1.61it/s]

(38, 3)


 32%|████████████▌                          | 323/1000 [02:18<06:11,  1.82it/s]

(36, 3)


 32%|████████████▋                          | 324/1000 [02:19<05:31,  2.04it/s]

(38, 3)


 32%|████████████▋                          | 325/1000 [02:19<05:18,  2.12it/s]

(38, 3)


 33%|████████████▋                          | 326/1000 [02:19<05:15,  2.13it/s]

(37, 3)


 33%|████████████▊                          | 327/1000 [02:20<04:59,  2.25it/s]

(38, 3)


 33%|████████████▊                          | 328/1000 [02:20<04:54,  2.28it/s]

(40, 3)


 33%|████████████▊                          | 329/1000 [02:21<05:15,  2.13it/s]

(44, 3)


 33%|████████████▊                          | 330/1000 [02:22<06:12,  1.80it/s]

(38, 3)


 33%|████████████▉                          | 331/1000 [02:22<05:28,  2.04it/s]

(37, 3)


 33%|████████████▉                          | 332/1000 [02:22<05:16,  2.11it/s]

(40, 3)


 33%|████████████▉                          | 333/1000 [02:23<05:27,  2.03it/s]

(38, 3)


 33%|█████████████                          | 334/1000 [02:24<06:39,  1.67it/s]

(39, 3)


 34%|█████████████                          | 335/1000 [02:24<07:17,  1.52it/s]

(43, 3)


 34%|█████████████                          | 336/1000 [02:25<06:47,  1.63it/s]

(43, 3)


 34%|█████████████▏                         | 337/1000 [02:26<06:33,  1.68it/s]

(37, 3)


 34%|█████████████▏                         | 338/1000 [02:26<06:06,  1.80it/s]

(46, 3)


 34%|█████████████▏                         | 339/1000 [02:26<05:57,  1.85it/s]

(44, 3)


 34%|█████████████▎                         | 340/1000 [02:27<05:46,  1.91it/s]

(44, 3)


 34%|█████████████▎                         | 341/1000 [02:28<06:44,  1.63it/s]

(43, 3)


 34%|█████████████▎                         | 342/1000 [02:28<06:17,  1.74it/s]

(42, 3)


 34%|█████████████▍                         | 343/1000 [02:29<05:49,  1.88it/s]

(43, 3)


 34%|█████████████▍                         | 344/1000 [02:29<05:13,  2.09it/s]

(40, 3)


 34%|█████████████▍                         | 345/1000 [02:29<04:40,  2.34it/s]

(35, 3)


 35%|█████████████▍                         | 346/1000 [02:30<04:16,  2.55it/s]

(35, 3)


 35%|█████████████▌                         | 347/1000 [02:30<03:58,  2.74it/s]

(35, 3)


 35%|█████████████▌                         | 348/1000 [02:31<06:06,  1.78it/s]

(36, 3)


 35%|█████████████▌                         | 349/1000 [02:32<07:26,  1.46it/s]

(47, 3)


 35%|█████████████▋                         | 350/1000 [02:33<07:51,  1.38it/s]

(40, 3)


 35%|█████████████▋                         | 351/1000 [02:33<07:26,  1.45it/s]

(40, 3)


 35%|█████████████▋                         | 352/1000 [02:34<06:29,  1.66it/s]

(41, 3)


 35%|█████████████▊                         | 353/1000 [02:34<05:56,  1.82it/s]

(41, 3)


 35%|█████████████▊                         | 354/1000 [02:35<05:49,  1.85it/s]

(43, 3)


 36%|█████████████▊                         | 355/1000 [02:35<05:31,  1.95it/s]

(42, 3)


 36%|█████████████▉                         | 356/1000 [02:35<04:47,  2.24it/s]

(35, 3)


 36%|█████████████▉                         | 357/1000 [02:36<04:35,  2.33it/s]

(40, 3)


 36%|█████████████▉                         | 358/1000 [02:37<05:19,  2.01it/s]

(39, 3)


 36%|██████████████                         | 359/1000 [02:37<05:07,  2.08it/s]

(40, 3)


 36%|██████████████                         | 360/1000 [02:37<04:44,  2.25it/s]

(39, 3)


 36%|██████████████                         | 361/1000 [02:38<04:19,  2.46it/s]

(35, 3)


 36%|██████████████                         | 362/1000 [02:38<04:44,  2.24it/s]

(39, 3)


 36%|██████████████▏                        | 363/1000 [02:38<04:14,  2.51it/s]

(36, 3)


 36%|██████████████▏                        | 364/1000 [02:39<04:29,  2.36it/s]

(37, 3)


 36%|██████████████▏                        | 365/1000 [02:39<04:40,  2.26it/s]

(37, 3)


 37%|██████████████▎                        | 366/1000 [02:40<04:17,  2.46it/s]

(37, 3)


 37%|██████████████▎                        | 367/1000 [02:40<04:57,  2.13it/s]

(41, 3)


 37%|██████████████▎                        | 368/1000 [02:41<04:47,  2.19it/s]

(40, 3)


 37%|██████████████▍                        | 369/1000 [02:41<04:22,  2.41it/s]

(37, 3)


 37%|██████████████▍                        | 370/1000 [02:41<04:08,  2.54it/s]

(37, 3)


 37%|██████████████▍                        | 371/1000 [02:42<05:22,  1.95it/s]

(36, 3)


 37%|██████████████▌                        | 372/1000 [02:43<04:44,  2.21it/s]

(39, 3)


 37%|██████████████▌                        | 373/1000 [02:43<05:24,  1.93it/s]

(43, 3)


 37%|██████████████▌                        | 374/1000 [02:44<06:09,  1.69it/s]

(40, 3)


 38%|██████████████▋                        | 375/1000 [02:44<05:19,  1.96it/s]

(37, 3)


 38%|██████████████▋                        | 376/1000 [02:45<04:52,  2.13it/s]

(37, 3)


 38%|██████████████▋                        | 377/1000 [02:45<04:32,  2.29it/s]

(38, 3)


 38%|██████████████▋                        | 378/1000 [02:45<04:08,  2.50it/s]

(39, 3)


 38%|██████████████▊                        | 379/1000 [02:46<05:11,  1.99it/s]

(40, 3)


 38%|██████████████▊                        | 380/1000 [02:46<04:32,  2.28it/s]

(37, 3)


 38%|██████████████▊                        | 381/1000 [02:47<04:39,  2.21it/s]

(37, 3)


 38%|██████████████▉                        | 382/1000 [02:47<04:08,  2.49it/s]

(38, 3)


 38%|██████████████▉                        | 383/1000 [02:48<04:47,  2.15it/s]

(38, 3)


 38%|██████████████▉                        | 384/1000 [02:48<04:16,  2.40it/s]

(37, 3)


 38%|███████████████                        | 385/1000 [02:48<03:53,  2.63it/s]

(36, 3)


 39%|███████████████                        | 386/1000 [02:49<04:01,  2.54it/s]

(43, 3)


 39%|███████████████                        | 387/1000 [02:49<03:26,  2.97it/s]

(36, 3)


 39%|███████████████▏                       | 388/1000 [02:50<05:47,  1.76it/s]

(36, 3)


 39%|███████████████▏                       | 389/1000 [02:50<04:49,  2.11it/s]

(34, 3)


 39%|███████████████▏                       | 390/1000 [02:51<04:31,  2.25it/s]

(40, 3)


 39%|███████████████▏                       | 391/1000 [02:51<04:54,  2.07it/s]

(37, 3)


 39%|███████████████▎                       | 392/1000 [02:53<07:30,  1.35it/s]

(43, 3)


 39%|███████████████▎                       | 393/1000 [02:53<06:13,  1.62it/s]

(37, 3)


 39%|███████████████▎                       | 394/1000 [02:54<06:13,  1.62it/s]

(37, 3)


 40%|███████████████▍                       | 395/1000 [02:54<05:51,  1.72it/s]

(40, 3)


 40%|███████████████▍                       | 396/1000 [02:55<05:35,  1.80it/s]

(37, 3)


 40%|███████████████▍                       | 397/1000 [02:55<04:51,  2.07it/s]

(39, 3)


 40%|███████████████▌                       | 398/1000 [02:55<04:17,  2.34it/s]

(37, 3)


 40%|███████████████▌                       | 399/1000 [02:56<05:39,  1.77it/s]

(42, 3)


 40%|███████████████▌                       | 400/1000 [02:57<05:44,  1.74it/s]

(40, 3)


 40%|███████████████▋                       | 401/1000 [02:57<05:07,  1.95it/s]

(42, 3)


 40%|███████████████▋                       | 402/1000 [02:58<04:49,  2.07it/s]

(40, 3)


 40%|███████████████▋                       | 403/1000 [02:58<04:48,  2.07it/s]

(39, 3)


 40%|███████████████▊                       | 404/1000 [02:58<04:14,  2.35it/s]

(40, 3)


 40%|███████████████▊                       | 405/1000 [02:59<03:55,  2.53it/s]

(39, 3)


 41%|███████████████▊                       | 406/1000 [02:59<04:03,  2.44it/s]

(39, 3)


 41%|███████████████▊                       | 407/1000 [02:59<03:29,  2.84it/s]

(38, 3)


 41%|███████████████▉                       | 408/1000 [03:00<03:12,  3.08it/s]

(42, 3)


 41%|███████████████▉                       | 409/1000 [03:00<04:04,  2.42it/s]

(40, 3)


 41%|███████████████▉                       | 410/1000 [03:01<03:54,  2.52it/s]

(39, 3)


 41%|████████████████                       | 411/1000 [03:01<04:09,  2.36it/s]

(38, 3)


 41%|████████████████                       | 412/1000 [03:01<03:40,  2.66it/s]

(39, 3)


 41%|████████████████                       | 413/1000 [03:02<03:18,  2.96it/s]

(40, 3)


 41%|████████████████▏                      | 414/1000 [03:02<03:08,  3.10it/s]

(38, 3)


 42%|████████████████▏                      | 415/1000 [03:02<02:55,  3.33it/s]

(36, 3)


 42%|████████████████▏                      | 416/1000 [03:02<03:08,  3.11it/s]

(41, 3)


 42%|████████████████▎                      | 417/1000 [03:03<03:28,  2.80it/s]

(43, 3)


 42%|████████████████▎                      | 418/1000 [03:03<04:11,  2.32it/s]

(41, 3)


 42%|████████████████▎                      | 419/1000 [03:04<04:26,  2.18it/s]

(48, 3)


 42%|████████████████▍                      | 420/1000 [03:04<04:31,  2.14it/s]

(40, 3)


 42%|████████████████▍                      | 421/1000 [03:05<03:55,  2.46it/s]

(36, 3)


 42%|████████████████▍                      | 422/1000 [03:05<03:28,  2.77it/s]

(36, 3)


 42%|████████████████▍                      | 423/1000 [03:06<04:27,  2.16it/s]

(36, 3)


 42%|████████████████▌                      | 424/1000 [03:06<05:24,  1.77it/s]

(38, 3)


 42%|████████████████▌                      | 425/1000 [03:07<04:30,  2.12it/s]

(35, 3)


 43%|████████████████▌                      | 426/1000 [03:07<03:51,  2.48it/s]

(34, 3)


 43%|████████████████▋                      | 427/1000 [03:08<06:49,  1.40it/s]

(39, 3)


 43%|████████████████▋                      | 428/1000 [03:09<05:28,  1.74it/s]

(34, 3)


 43%|████████████████▋                      | 429/1000 [03:09<05:16,  1.80it/s]

(37, 3)


 43%|████████████████▊                      | 430/1000 [03:10<05:39,  1.68it/s]

(37, 3)


 43%|████████████████▊                      | 431/1000 [03:10<05:01,  1.89it/s]

(36, 3)


 43%|████████████████▊                      | 432/1000 [03:11<04:13,  2.24it/s]

(36, 3)


 43%|████████████████▉                      | 433/1000 [03:11<04:04,  2.32it/s]

(36, 3)


 43%|████████████████▉                      | 434/1000 [03:11<03:51,  2.45it/s]

(35, 3)


 44%|████████████████▉                      | 435/1000 [03:11<03:22,  2.80it/s]

(35, 3)


 44%|█████████████████                      | 436/1000 [03:12<03:06,  3.03it/s]

(42, 3)


 44%|█████████████████                      | 437/1000 [03:12<03:01,  3.11it/s]

(40, 3)


 44%|█████████████████                      | 438/1000 [03:12<02:56,  3.18it/s]

(39, 3)


 44%|█████████████████                      | 439/1000 [03:13<02:54,  3.22it/s]

(39, 3)


 44%|█████████████████▏                     | 440/1000 [03:13<02:53,  3.23it/s]

(41, 3)


 44%|█████████████████▏                     | 441/1000 [03:13<02:55,  3.18it/s]

(38, 3)


 44%|█████████████████▏                     | 442/1000 [03:14<03:14,  2.88it/s]

(42, 3)


 44%|█████████████████▎                     | 443/1000 [03:14<03:17,  2.82it/s]

(41, 3)


 44%|█████████████████▎                     | 444/1000 [03:15<03:46,  2.45it/s]

(37, 3)


 44%|█████████████████▎                     | 445/1000 [03:15<03:30,  2.63it/s]

(39, 3)


 45%|█████████████████▍                     | 446/1000 [03:15<03:08,  2.95it/s]

(39, 3)


 45%|█████████████████▍                     | 447/1000 [03:15<02:53,  3.19it/s]

(39, 3)


 45%|█████████████████▍                     | 448/1000 [03:16<03:29,  2.64it/s]

(39, 3)


 45%|█████████████████▌                     | 449/1000 [03:16<03:15,  2.82it/s]

(39, 3)


 45%|█████████████████▌                     | 450/1000 [03:17<03:10,  2.89it/s]

(39, 3)


 45%|█████████████████▌                     | 451/1000 [03:17<03:24,  2.68it/s]

(46, 3)


 45%|█████████████████▋                     | 452/1000 [03:18<03:46,  2.42it/s]

(39, 3)


 45%|█████████████████▋                     | 453/1000 [03:18<03:33,  2.57it/s]

(38, 3)


 45%|█████████████████▋                     | 454/1000 [03:18<03:53,  2.34it/s]

(48, 3)


 46%|█████████████████▋                     | 455/1000 [03:19<03:35,  2.53it/s]

(38, 3)


 46%|█████████████████▊                     | 456/1000 [03:21<07:37,  1.19it/s]

(39, 3)


 46%|█████████████████▊                     | 457/1000 [03:21<06:10,  1.47it/s]

(41, 3)


 46%|█████████████████▊                     | 458/1000 [03:21<05:16,  1.71it/s]

(39, 3)


 46%|█████████████████▉                     | 459/1000 [03:22<04:41,  1.92it/s]

(39, 3)


 46%|█████████████████▉                     | 460/1000 [03:22<04:05,  2.20it/s]

(39, 3)


 46%|█████████████████▉                     | 461/1000 [03:22<03:55,  2.29it/s]

(38, 3)


 46%|██████████████████                     | 462/1000 [03:23<04:17,  2.09it/s]

(38, 3)


 46%|██████████████████                     | 463/1000 [03:23<03:52,  2.31it/s]

(38, 3)


 46%|██████████████████                     | 464/1000 [03:24<03:45,  2.38it/s]

(39, 3)


 46%|██████████████████▏                    | 465/1000 [03:24<03:18,  2.69it/s]

(34, 3)


 47%|██████████████████▏                    | 466/1000 [03:24<03:10,  2.81it/s]

(40, 3)


 47%|██████████████████▏                    | 467/1000 [03:24<02:53,  3.07it/s]

(37, 3)


 47%|██████████████████▎                    | 468/1000 [03:25<02:47,  3.17it/s]

(37, 3)


 47%|██████████████████▎                    | 469/1000 [03:25<03:01,  2.93it/s]

(39, 3)


 47%|██████████████████▎                    | 470/1000 [03:25<02:49,  3.12it/s]

(36, 3)


 47%|██████████████████▎                    | 471/1000 [03:26<02:53,  3.06it/s]

(41, 3)


 47%|██████████████████▍                    | 472/1000 [03:26<02:42,  3.24it/s]

(36, 3)


 47%|██████████████████▍                    | 473/1000 [03:26<02:30,  3.50it/s]

(36, 3)


 47%|██████████████████▍                    | 474/1000 [03:27<02:46,  3.15it/s]

(37, 3)


 48%|██████████████████▌                    | 475/1000 [03:27<03:26,  2.54it/s]

(34, 3)


 48%|██████████████████▌                    | 476/1000 [03:27<03:07,  2.79it/s]

(34, 3)


 48%|██████████████████▌                    | 477/1000 [03:28<04:12,  2.07it/s]

(36, 3)


 48%|██████████████████▋                    | 478/1000 [03:28<03:30,  2.48it/s]

(37, 3)


 48%|██████████████████▋                    | 479/1000 [03:29<04:46,  1.82it/s]

(38, 3)


 48%|██████████████████▋                    | 480/1000 [03:30<04:05,  2.12it/s]

(38, 3)


 48%|██████████████████▊                    | 481/1000 [03:31<07:02,  1.23it/s]

(44, 3)


 48%|██████████████████▊                    | 482/1000 [03:31<05:30,  1.57it/s]

(35, 3)


 48%|██████████████████▊                    | 483/1000 [03:32<04:58,  1.73it/s]

(34, 3)


 48%|██████████████████▉                    | 484/1000 [03:33<05:13,  1.65it/s]

(41, 3)


 48%|██████████████████▉                    | 485/1000 [03:33<04:26,  1.93it/s]

(37, 3)


 49%|██████████████████▉                    | 486/1000 [03:34<04:41,  1.82it/s]

(40, 3)


 49%|██████████████████▉                    | 487/1000 [03:34<04:10,  2.04it/s]

(40, 3)


 49%|███████████████████                    | 488/1000 [03:34<03:40,  2.33it/s]

(37, 3)


 49%|███████████████████                    | 489/1000 [03:35<03:23,  2.51it/s]

(37, 3)


 49%|███████████████████                    | 490/1000 [03:35<03:03,  2.78it/s]

(33, 3)


 49%|███████████████████▏                   | 491/1000 [03:35<03:03,  2.78it/s]

(37, 3)


 49%|███████████████████▏                   | 492/1000 [03:36<03:19,  2.54it/s]

(36, 3)


 49%|███████████████████▏                   | 493/1000 [03:36<03:08,  2.69it/s]

(36, 3)


 49%|███████████████████▎                   | 494/1000 [03:36<03:03,  2.76it/s]

(36, 3)


 50%|███████████████████▎                   | 495/1000 [03:37<03:00,  2.80it/s]

(35, 3)


 50%|███████████████████▎                   | 496/1000 [03:37<04:00,  2.09it/s]

(35, 3)


 50%|███████████████████▍                   | 497/1000 [03:38<03:32,  2.36it/s]

(35, 3)


 50%|███████████████████▍                   | 498/1000 [03:38<03:41,  2.27it/s]

(39, 3)


 50%|███████████████████▍                   | 499/1000 [03:38<03:20,  2.50it/s]

(38, 3)


 50%|███████████████████▌                   | 500/1000 [03:39<03:24,  2.44it/s]

(43, 3)


 50%|███████████████████▌                   | 501/1000 [03:40<04:06,  2.02it/s]

(47, 3)


 50%|███████████████████▌                   | 502/1000 [03:40<04:34,  1.81it/s]

(46, 3)


 50%|███████████████████▌                   | 503/1000 [03:41<04:29,  1.85it/s]

(45, 3)


 50%|███████████████████▋                   | 504/1000 [03:41<04:42,  1.76it/s]

(38, 3)


 50%|███████████████████▋                   | 505/1000 [03:42<04:22,  1.89it/s]

(40, 3)


 51%|███████████████████▋                   | 506/1000 [03:42<03:50,  2.14it/s]

(39, 3)


 51%|███████████████████▊                   | 507/1000 [03:43<03:38,  2.26it/s]

(39, 3)


 51%|███████████████████▊                   | 508/1000 [03:43<04:10,  1.96it/s]

(40, 3)


 51%|███████████████████▊                   | 509/1000 [03:44<03:53,  2.10it/s]

(39, 3)


 51%|███████████████████▉                   | 510/1000 [03:44<03:57,  2.06it/s]

(46, 3)


 51%|███████████████████▉                   | 511/1000 [03:44<03:37,  2.24it/s]

(38, 3)


 51%|███████████████████▉                   | 512/1000 [03:45<03:18,  2.46it/s]

(38, 3)


 51%|████████████████████                   | 513/1000 [03:45<03:55,  2.07it/s]

(36, 3)


 51%|████████████████████                   | 514/1000 [03:46<04:51,  1.67it/s]

(38, 3)


 52%|████████████████████                   | 515/1000 [03:47<04:11,  1.93it/s]

(36, 3)


 52%|████████████████████                   | 516/1000 [03:47<03:47,  2.13it/s]

(37, 3)


 52%|████████████████████▏                  | 517/1000 [03:47<03:28,  2.32it/s]

(40, 3)


 52%|████████████████████▏                  | 518/1000 [03:48<03:30,  2.29it/s]

(35, 3)


 52%|████████████████████▏                  | 519/1000 [03:48<03:58,  2.02it/s]

(39, 3)


 52%|████████████████████▎                  | 520/1000 [03:49<03:45,  2.13it/s]

(40, 3)


 52%|████████████████████▎                  | 521/1000 [03:49<03:29,  2.28it/s]

(37, 3)


 52%|████████████████████▎                  | 522/1000 [03:50<03:09,  2.52it/s]

(34, 3)


 52%|████████████████████▍                  | 523/1000 [03:50<03:08,  2.54it/s]

(38, 3)


 52%|████████████████████▍                  | 524/1000 [03:50<02:59,  2.65it/s]

(34, 3)


 52%|████████████████████▍                  | 525/1000 [03:52<05:27,  1.45it/s]

(39, 3)


 53%|████████████████████▌                  | 526/1000 [03:52<05:20,  1.48it/s]

(39, 3)


 53%|████████████████████▌                  | 527/1000 [03:53<06:06,  1.29it/s]

(38, 3)


 53%|████████████████████▌                  | 528/1000 [03:54<05:41,  1.38it/s]

(41, 3)


 53%|████████████████████▋                  | 529/1000 [03:55<06:41,  1.17it/s]

(44, 3)


 53%|████████████████████▋                  | 530/1000 [03:56<07:14,  1.08it/s]

(41, 3)


 53%|████████████████████▋                  | 531/1000 [03:57<05:56,  1.32it/s]

(38, 3)


 53%|████████████████████▋                  | 532/1000 [03:57<04:58,  1.57it/s]

(37, 3)


 53%|████████████████████▊                  | 533/1000 [03:58<05:10,  1.51it/s]

(37, 3)


 53%|████████████████████▊                  | 534/1000 [03:58<04:54,  1.58it/s]

(40, 3)


 54%|████████████████████▊                  | 535/1000 [03:59<05:17,  1.46it/s]

(42, 3)


 54%|████████████████████▉                  | 536/1000 [03:59<04:47,  1.61it/s]

(43, 3)


 54%|████████████████████▉                  | 537/1000 [04:00<04:04,  1.90it/s]

(40, 3)


 54%|████████████████████▉                  | 538/1000 [04:00<03:28,  2.22it/s]

(34, 3)


 54%|█████████████████████                  | 539/1000 [04:00<03:20,  2.30it/s]

(36, 3)


 54%|█████████████████████                  | 540/1000 [04:01<03:26,  2.23it/s]

(41, 3)


 54%|█████████████████████                  | 541/1000 [04:02<04:17,  1.78it/s]

(47, 3)


 54%|█████████████████████▏                 | 542/1000 [04:03<04:46,  1.60it/s]

(39, 3)


 54%|█████████████████████▏                 | 543/1000 [04:03<04:31,  1.68it/s]

(44, 3)


 54%|█████████████████████▏                 | 544/1000 [04:03<03:55,  1.94it/s]

(40, 3)


 55%|█████████████████████▎                 | 545/1000 [04:04<03:37,  2.09it/s]

(39, 3)


 55%|█████████████████████▎                 | 546/1000 [04:04<03:23,  2.24it/s]

(39, 3)


 55%|█████████████████████▎                 | 547/1000 [04:05<03:48,  1.99it/s]

(40, 3)


 55%|█████████████████████▎                 | 548/1000 [04:05<03:31,  2.13it/s]

(39, 3)


 55%|█████████████████████▍                 | 549/1000 [04:06<04:25,  1.70it/s]

(40, 3)


 55%|█████████████████████▍                 | 550/1000 [04:07<04:27,  1.69it/s]

(40, 3)


 55%|█████████████████████▍                 | 551/1000 [04:07<04:02,  1.85it/s]

(39, 3)


 55%|█████████████████████▌                 | 552/1000 [04:08<04:35,  1.62it/s]

(39, 3)


 55%|█████████████████████▌                 | 553/1000 [04:08<04:00,  1.86it/s]

(40, 3)


 55%|█████████████████████▌                 | 554/1000 [04:09<04:13,  1.76it/s]

(39, 3)


 56%|█████████████████████▋                 | 555/1000 [04:09<03:37,  2.04it/s]

(39, 3)


 56%|█████████████████████▋                 | 556/1000 [04:11<05:43,  1.29it/s]

(40, 3)


 56%|█████████████████████▋                 | 557/1000 [04:11<05:33,  1.33it/s]

(43, 3)


 56%|█████████████████████▊                 | 558/1000 [04:12<04:57,  1.49it/s]

(38, 3)


 56%|█████████████████████▊                 | 559/1000 [04:13<05:10,  1.42it/s]

(39, 3)


 56%|█████████████████████▊                 | 560/1000 [04:13<04:20,  1.69it/s]

(35, 3)


 56%|█████████████████████▉                 | 561/1000 [04:13<03:52,  1.89it/s]

(38, 3)


 56%|█████████████████████▉                 | 562/1000 [04:14<03:30,  2.08it/s]

(39, 3)


 56%|█████████████████████▉                 | 563/1000 [04:14<03:32,  2.06it/s]

(36, 3)


 56%|█████████████████████▉                 | 564/1000 [04:15<03:45,  1.93it/s]

(37, 3)


 56%|██████████████████████                 | 565/1000 [04:15<03:43,  1.95it/s]

(40, 3)


 57%|██████████████████████                 | 566/1000 [04:15<03:10,  2.27it/s]

(37, 3)


 57%|██████████████████████                 | 567/1000 [04:16<02:54,  2.48it/s]

(40, 3)


 57%|██████████████████████▏                | 568/1000 [04:16<02:41,  2.68it/s]

(39, 3)


 57%|██████████████████████▏                | 569/1000 [04:17<03:47,  1.89it/s]

(38, 3)


 57%|██████████████████████▏                | 570/1000 [04:17<03:34,  2.01it/s]

(39, 3)


 57%|██████████████████████▎                | 571/1000 [04:18<03:27,  2.07it/s]

(39, 3)


 57%|██████████████████████▎                | 572/1000 [04:18<03:33,  2.01it/s]

(39, 3)


 57%|██████████████████████▎                | 573/1000 [04:19<03:12,  2.22it/s]

(39, 3)


 57%|██████████████████████▍                | 574/1000 [04:19<03:30,  2.02it/s]

(45, 3)


 57%|██████████████████████▍                | 575/1000 [04:20<03:05,  2.29it/s]

(41, 3)


 58%|██████████████████████▍                | 576/1000 [04:20<02:47,  2.52it/s]

(38, 3)


 58%|██████████████████████▌                | 577/1000 [04:20<02:32,  2.78it/s]

(37, 3)


 58%|██████████████████████▌                | 578/1000 [04:21<02:50,  2.48it/s]

(39, 3)


 58%|██████████████████████▌                | 579/1000 [04:21<02:42,  2.59it/s]

(40, 3)


 58%|██████████████████████▌                | 580/1000 [04:22<03:51,  1.81it/s]

(47, 3)


 58%|██████████████████████▋                | 581/1000 [04:23<03:57,  1.76it/s]

(43, 3)


 58%|██████████████████████▋                | 582/1000 [04:23<03:28,  2.01it/s]

(43, 3)


 58%|██████████████████████▋                | 583/1000 [04:23<03:14,  2.15it/s]

(43, 3)


 58%|██████████████████████▊                | 584/1000 [04:24<03:07,  2.22it/s]

(43, 3)


 58%|██████████████████████▊                | 585/1000 [04:24<02:40,  2.58it/s]

(36, 3)


 59%|██████████████████████▊                | 586/1000 [04:24<02:23,  2.88it/s]

(37, 3)


 59%|██████████████████████▉                | 587/1000 [04:25<03:25,  2.01it/s]

(46, 3)


 59%|██████████████████████▉                | 588/1000 [04:25<02:57,  2.32it/s]

(40, 3)


 59%|██████████████████████▉                | 589/1000 [04:26<02:44,  2.49it/s]

(42, 3)


 59%|███████████████████████                | 590/1000 [04:26<02:24,  2.83it/s]

(38, 3)


 59%|███████████████████████                | 591/1000 [04:26<02:28,  2.75it/s]

(40, 3)


 59%|███████████████████████                | 592/1000 [04:27<02:22,  2.87it/s]

(41, 3)


 59%|███████████████████████▏               | 593/1000 [04:27<02:33,  2.65it/s]

(40, 3)


 59%|███████████████████████▏               | 594/1000 [04:28<02:40,  2.53it/s]

(40, 3)


 60%|███████████████████████▏               | 595/1000 [04:28<03:06,  2.17it/s]

(40, 3)


 60%|███████████████████████▏               | 596/1000 [04:28<02:44,  2.46it/s]

(40, 3)


 60%|███████████████████████▎               | 597/1000 [04:29<02:23,  2.80it/s]

(38, 3)


 60%|███████████████████████▎               | 598/1000 [04:29<02:42,  2.47it/s]

(43, 3)


 60%|███████████████████████▎               | 599/1000 [04:29<02:25,  2.75it/s]

(40, 3)


 60%|███████████████████████▍               | 600/1000 [04:30<02:18,  2.88it/s]

(40, 3)


 60%|███████████████████████▍               | 601/1000 [04:30<02:11,  3.04it/s]

(42, 3)


 60%|███████████████████████▍               | 602/1000 [04:31<02:52,  2.31it/s]

(39, 3)


 60%|███████████████████████▌               | 603/1000 [04:31<02:30,  2.64it/s]

(39, 3)


 60%|███████████████████████▌               | 604/1000 [04:31<02:13,  2.96it/s]

(38, 3)


 60%|███████████████████████▌               | 605/1000 [04:32<02:53,  2.27it/s]

(39, 3)


 61%|███████████████████████▋               | 606/1000 [04:32<03:09,  2.08it/s]

(39, 3)


 61%|███████████████████████▋               | 607/1000 [04:33<03:09,  2.07it/s]

(38, 3)


 61%|███████████████████████▋               | 608/1000 [04:33<02:45,  2.36it/s]

(39, 3)


 61%|███████████████████████▊               | 609/1000 [04:33<02:23,  2.72it/s]

(39, 3)


 61%|███████████████████████▊               | 610/1000 [04:34<02:53,  2.25it/s]

(38, 3)


 61%|███████████████████████▊               | 611/1000 [04:34<02:47,  2.33it/s]

(45, 3)


 61%|███████████████████████▊               | 612/1000 [04:35<02:46,  2.33it/s]

(39, 3)


 61%|███████████████████████▉               | 613/1000 [04:36<03:51,  1.67it/s]

(39, 3)


 61%|███████████████████████▉               | 614/1000 [04:36<03:25,  1.88it/s]

(38, 3)


 62%|███████████████████████▉               | 615/1000 [04:37<03:53,  1.65it/s]

(37, 3)


 62%|████████████████████████               | 616/1000 [04:37<03:19,  1.93it/s]

(39, 3)


 62%|████████████████████████               | 617/1000 [04:38<03:31,  1.81it/s]

(38, 3)


 62%|████████████████████████               | 618/1000 [04:38<03:15,  1.95it/s]

(37, 3)


 62%|████████████████████████▏              | 619/1000 [04:40<05:50,  1.09it/s]

(41, 3)


 62%|████████████████████████▏              | 620/1000 [04:41<04:52,  1.30it/s]

(36, 3)


 62%|████████████████████████▏              | 621/1000 [04:41<03:55,  1.61it/s]

(37, 3)


 62%|████████████████████████▎              | 622/1000 [04:41<03:38,  1.73it/s]

(38, 3)


 62%|████████████████████████▎              | 623/1000 [04:42<03:10,  1.98it/s]

(39, 3)


 62%|████████████████████████▎              | 624/1000 [04:42<02:57,  2.12it/s]

(37, 3)


 62%|████████████████████████▍              | 625/1000 [04:42<02:33,  2.44it/s]

(36, 3)


 63%|████████████████████████▍              | 626/1000 [04:43<03:05,  2.01it/s]

(36, 3)


 63%|████████████████████████▍              | 627/1000 [04:43<02:37,  2.36it/s]

(39, 3)


 63%|████████████████████████▍              | 628/1000 [04:44<02:52,  2.15it/s]

(42, 3)


 63%|████████████████████████▌              | 629/1000 [04:44<02:27,  2.51it/s]

(38, 3)


 63%|████████████████████████▌              | 630/1000 [04:44<02:12,  2.79it/s]

(38, 3)


 63%|████████████████████████▌              | 631/1000 [04:45<02:32,  2.42it/s]

(38, 3)


 63%|████████████████████████▋              | 632/1000 [04:46<02:55,  2.09it/s]

(40, 3)


 63%|████████████████████████▋              | 633/1000 [04:46<02:32,  2.40it/s]

(38, 3)


 63%|████████████████████████▋              | 634/1000 [04:46<02:24,  2.53it/s]

(39, 3)


 64%|████████████████████████▊              | 635/1000 [04:47<02:06,  2.88it/s]

(37, 3)


 64%|████████████████████████▊              | 636/1000 [04:47<02:07,  2.86it/s]

(38, 3)


 64%|████████████████████████▊              | 637/1000 [04:47<01:58,  3.06it/s]

(39, 3)


 64%|████████████████████████▉              | 638/1000 [04:48<02:31,  2.38it/s]

(44, 3)


 64%|████████████████████████▉              | 639/1000 [04:49<03:38,  1.65it/s]

(47, 3)


 64%|████████████████████████▉              | 640/1000 [04:49<03:11,  1.88it/s]

(39, 3)


 64%|████████████████████████▉              | 641/1000 [04:50<03:31,  1.70it/s]

(45, 3)


 64%|█████████████████████████              | 642/1000 [04:51<04:06,  1.45it/s]

(38, 3)


 64%|█████████████████████████              | 643/1000 [04:51<03:18,  1.80it/s]

(38, 3)


 64%|█████████████████████████              | 644/1000 [04:51<02:44,  2.16it/s]

(38, 3)


 64%|█████████████████████████▏             | 645/1000 [04:52<02:55,  2.02it/s]

(39, 3)


 65%|█████████████████████████▏             | 646/1000 [04:52<02:28,  2.38it/s]

(37, 3)


 65%|█████████████████████████▏             | 647/1000 [04:53<02:49,  2.08it/s]

(37, 3)


 65%|█████████████████████████▎             | 648/1000 [04:53<02:28,  2.38it/s]

(39, 3)


 65%|█████████████████████████▎             | 649/1000 [04:54<04:06,  1.42it/s]

(40, 3)


 65%|█████████████████████████▎             | 650/1000 [04:55<03:19,  1.75it/s]

(40, 3)


 65%|█████████████████████████▍             | 651/1000 [04:55<02:47,  2.09it/s]

(41, 3)


 65%|█████████████████████████▍             | 652/1000 [04:55<02:27,  2.36it/s]

(42, 3)


 65%|█████████████████████████▍             | 653/1000 [04:55<02:10,  2.66it/s]

(39, 3)


 65%|█████████████████████████▌             | 654/1000 [04:56<01:56,  2.98it/s]

(37, 3)


 66%|█████████████████████████▌             | 655/1000 [04:56<01:50,  3.12it/s]

(42, 3)


 66%|█████████████████████████▌             | 656/1000 [04:57<02:10,  2.64it/s]

(37, 3)


 66%|█████████████████████████▌             | 657/1000 [04:57<02:06,  2.72it/s]

(37, 3)


 66%|█████████████████████████▋             | 658/1000 [04:57<01:54,  3.00it/s]

(38, 3)


 66%|█████████████████████████▋             | 659/1000 [04:57<01:46,  3.20it/s]

(38, 3)


 66%|█████████████████████████▋             | 660/1000 [04:58<02:05,  2.71it/s]

(37, 3)


 66%|█████████████████████████▊             | 661/1000 [04:58<01:59,  2.84it/s]

(37, 3)


 66%|█████████████████████████▊             | 662/1000 [04:58<01:46,  3.17it/s]

(37, 3)


 66%|█████████████████████████▊             | 663/1000 [04:59<01:42,  3.30it/s]

(37, 3)


 66%|█████████████████████████▉             | 664/1000 [04:59<01:48,  3.09it/s]

(38, 3)


 66%|█████████████████████████▉             | 665/1000 [04:59<01:51,  3.00it/s]

(39, 3)


 67%|█████████████████████████▉             | 666/1000 [05:00<02:51,  1.94it/s]

(38, 3)


 67%|██████████████████████████             | 667/1000 [05:01<02:40,  2.07it/s]

(41, 3)


 67%|██████████████████████████             | 668/1000 [05:01<02:35,  2.13it/s]

(37, 3)


 67%|██████████████████████████             | 669/1000 [05:02<02:23,  2.31it/s]

(37, 3)


 67%|██████████████████████████▏            | 670/1000 [05:02<02:18,  2.38it/s]

(41, 3)


 67%|██████████████████████████▏            | 671/1000 [05:02<02:02,  2.68it/s]

(38, 3)


 67%|██████████████████████████▏            | 672/1000 [05:03<01:59,  2.74it/s]

(45, 3)


 67%|██████████████████████████▏            | 673/1000 [05:03<01:50,  2.96it/s]

(40, 3)


 67%|██████████████████████████▎            | 674/1000 [05:03<01:42,  3.17it/s]

(39, 3)


 68%|██████████████████████████▎            | 675/1000 [05:03<01:37,  3.35it/s]

(40, 3)


 68%|██████████████████████████▎            | 676/1000 [05:04<01:32,  3.49it/s]

(39, 3)


 68%|██████████████████████████▍            | 677/1000 [05:04<01:30,  3.58it/s]

(37, 3)


 68%|██████████████████████████▍            | 678/1000 [05:04<01:33,  3.44it/s]

(36, 3)


 68%|██████████████████████████▍            | 679/1000 [05:05<01:36,  3.33it/s]

(36, 3)


 68%|██████████████████████████▌            | 680/1000 [05:05<01:39,  3.20it/s]

(38, 3)


 68%|██████████████████████████▌            | 681/1000 [05:05<01:49,  2.91it/s]

(38, 3)


 68%|██████████████████████████▌            | 682/1000 [05:05<01:37,  3.27it/s]

(34, 3)


 68%|██████████████████████████▋            | 683/1000 [05:06<01:58,  2.68it/s]

(37, 3)


 68%|██████████████████████████▋            | 684/1000 [05:06<02:00,  2.62it/s]

(37, 3)


 68%|██████████████████████████▋            | 685/1000 [05:07<02:29,  2.11it/s]

(41, 3)


 69%|██████████████████████████▊            | 686/1000 [05:07<02:05,  2.50it/s]

(38, 3)


 69%|██████████████████████████▊            | 687/1000 [05:08<02:02,  2.56it/s]

(37, 3)


 69%|██████████████████████████▊            | 688/1000 [05:08<02:03,  2.53it/s]

(44, 3)


 69%|██████████████████████████▊            | 689/1000 [05:08<01:52,  2.78it/s]

(41, 3)


 69%|██████████████████████████▉            | 690/1000 [05:09<01:43,  2.99it/s]

(39, 3)


 69%|██████████████████████████▉            | 691/1000 [05:09<01:49,  2.81it/s]

(37, 3)


 69%|██████████████████████████▉            | 692/1000 [05:09<01:35,  3.22it/s]

(37, 3)


 69%|███████████████████████████            | 693/1000 [05:10<01:42,  3.00it/s]

(37, 3)


 69%|███████████████████████████            | 694/1000 [05:10<01:33,  3.27it/s]

(38, 3)


 70%|███████████████████████████            | 695/1000 [05:10<01:43,  2.95it/s]

(46, 3)


 70%|███████████████████████████▏           | 696/1000 [05:11<01:39,  3.06it/s]

(38, 3)


 70%|███████████████████████████▏           | 697/1000 [05:11<01:33,  3.23it/s]

(37, 3)


 70%|███████████████████████████▏           | 698/1000 [05:11<01:45,  2.86it/s]

(37, 3)


 70%|███████████████████████████▎           | 699/1000 [05:12<01:47,  2.80it/s]

(37, 3)


 70%|███████████████████████████▎           | 700/1000 [05:12<02:20,  2.13it/s]

(37, 3)


 70%|███████████████████████████▎           | 701/1000 [05:13<01:59,  2.51it/s]

(37, 3)


 70%|███████████████████████████▍           | 702/1000 [05:13<01:48,  2.74it/s]

(37, 3)


 70%|███████████████████████████▍           | 703/1000 [05:13<01:53,  2.61it/s]

(37, 3)


 70%|███████████████████████████▍           | 704/1000 [05:14<01:46,  2.78it/s]

(41, 3)


 70%|███████████████████████████▍           | 705/1000 [05:14<01:53,  2.60it/s]

(38, 3)


 71%|███████████████████████████▌           | 706/1000 [05:14<01:47,  2.75it/s]

(35, 3)


 71%|███████████████████████████▌           | 707/1000 [05:15<01:39,  2.94it/s]

(39, 3)


 71%|███████████████████████████▌           | 708/1000 [05:15<01:29,  3.25it/s]

(36, 3)


 71%|███████████████████████████▋           | 709/1000 [05:15<01:22,  3.52it/s]

(36, 3)


 71%|███████████████████████████▋           | 710/1000 [05:16<01:39,  2.93it/s]

(37, 3)


 71%|███████████████████████████▋           | 711/1000 [05:16<01:41,  2.86it/s]

(37, 3)


 71%|███████████████████████████▊           | 712/1000 [05:16<01:32,  3.11it/s]

(40, 3)


 71%|███████████████████████████▊           | 713/1000 [05:17<01:37,  2.95it/s]

(40, 3)


 71%|███████████████████████████▊           | 714/1000 [05:18<02:34,  1.85it/s]

(40, 3)


 72%|███████████████████████████▉           | 715/1000 [05:18<02:08,  2.21it/s]

(38, 3)


 72%|███████████████████████████▉           | 716/1000 [05:18<02:10,  2.17it/s]

(38, 3)


 72%|███████████████████████████▉           | 717/1000 [05:19<01:59,  2.36it/s]

(38, 3)


 72%|████████████████████████████           | 718/1000 [05:19<01:56,  2.42it/s]

(43, 3)


 72%|████████████████████████████           | 719/1000 [05:19<01:43,  2.71it/s]

(37, 3)


 72%|████████████████████████████           | 720/1000 [05:20<01:35,  2.93it/s]

(38, 3)


 72%|████████████████████████████           | 721/1000 [05:20<01:27,  3.20it/s]

(37, 3)


 72%|████████████████████████████▏          | 722/1000 [05:20<01:20,  3.47it/s]

(37, 3)


 72%|████████████████████████████▏          | 723/1000 [05:21<01:37,  2.84it/s]

(38, 3)


 72%|████████████████████████████▏          | 724/1000 [05:21<02:11,  2.10it/s]

(37, 3)


 72%|████████████████████████████▎          | 725/1000 [05:22<01:51,  2.47it/s]

(37, 3)


 73%|████████████████████████████▎          | 726/1000 [05:22<01:36,  2.84it/s]

(36, 3)


 73%|████████████████████████████▎          | 727/1000 [05:22<01:30,  3.01it/s]

(40, 3)


 73%|████████████████████████████▍          | 728/1000 [05:23<02:36,  1.73it/s]

(39, 3)


 73%|████████████████████████████▍          | 729/1000 [05:24<02:25,  1.86it/s]

(40, 3)


 73%|████████████████████████████▍          | 730/1000 [05:24<02:04,  2.17it/s]

(39, 3)


 73%|████████████████████████████▌          | 731/1000 [05:24<01:46,  2.54it/s]

(37, 3)


 73%|████████████████████████████▌          | 732/1000 [05:25<01:57,  2.27it/s]

(41, 3)


 73%|████████████████████████████▌          | 733/1000 [05:25<01:46,  2.50it/s]

(41, 3)


 73%|████████████████████████████▋          | 734/1000 [05:25<01:34,  2.81it/s]

(39, 3)


 74%|████████████████████████████▋          | 735/1000 [05:26<01:28,  2.98it/s]

(37, 3)


 74%|████████████████████████████▋          | 737/1000 [05:26<01:12,  3.62it/s]

(36, 3)
(36, 3)


 74%|████████████████████████████▊          | 738/1000 [05:27<01:42,  2.55it/s]

(45, 3)


 74%|████████████████████████████▊          | 739/1000 [05:27<01:50,  2.37it/s]

(36, 3)


 74%|████████████████████████████▊          | 740/1000 [05:28<01:37,  2.65it/s]

(36, 3)


 74%|████████████████████████████▉          | 741/1000 [05:28<02:09,  2.00it/s]

(37, 3)


 74%|████████████████████████████▉          | 742/1000 [05:29<01:47,  2.39it/s]

(37, 3)


 74%|████████████████████████████▉          | 743/1000 [05:29<01:44,  2.47it/s]

(38, 3)


 74%|█████████████████████████████          | 744/1000 [05:29<01:28,  2.88it/s]

(35, 3)


 74%|█████████████████████████████          | 745/1000 [05:30<01:40,  2.53it/s]

(37, 3)


 75%|█████████████████████████████          | 746/1000 [05:30<01:27,  2.89it/s]

(36, 3)


 75%|█████████████████████████████▏         | 747/1000 [05:30<01:26,  2.93it/s]

(35, 3)


 75%|█████████████████████████████▏         | 748/1000 [05:31<01:25,  2.94it/s]

(36, 3)


 75%|█████████████████████████████▏         | 749/1000 [05:31<01:18,  3.20it/s]

(36, 3)


 75%|█████████████████████████████▎         | 750/1000 [05:31<01:15,  3.31it/s]

(38, 3)


 75%|█████████████████████████████▎         | 751/1000 [05:31<01:17,  3.20it/s]

(40, 3)


 75%|█████████████████████████████▎         | 752/1000 [05:32<01:11,  3.46it/s]

(37, 3)


 75%|█████████████████████████████▎         | 753/1000 [05:32<01:17,  3.18it/s]

(37, 3)


 75%|█████████████████████████████▍         | 754/1000 [05:32<01:19,  3.11it/s]

(38, 3)


 76%|█████████████████████████████▍         | 755/1000 [05:33<02:03,  1.99it/s]

(37, 3)


 76%|█████████████████████████████▍         | 756/1000 [05:34<02:09,  1.89it/s]

(37, 3)


 76%|█████████████████████████████▌         | 757/1000 [05:35<02:31,  1.61it/s]

(39, 3)


 76%|█████████████████████████████▌         | 758/1000 [05:35<02:06,  1.91it/s]

(37, 3)


 76%|█████████████████████████████▌         | 759/1000 [05:35<01:48,  2.21it/s]

(36, 3)


 76%|█████████████████████████████▋         | 760/1000 [05:36<02:01,  1.98it/s]

(42, 3)


 76%|█████████████████████████████▋         | 761/1000 [05:36<01:46,  2.25it/s]

(41, 3)


 76%|█████████████████████████████▋         | 762/1000 [05:37<01:47,  2.22it/s]

(39, 3)


 76%|█████████████████████████████▊         | 763/1000 [05:37<01:35,  2.49it/s]

(38, 3)


 76%|█████████████████████████████▊         | 764/1000 [05:37<01:21,  2.89it/s]

(35, 3)


 76%|█████████████████████████████▊         | 765/1000 [05:37<01:12,  3.23it/s]

(35, 3)


 77%|█████████████████████████████▊         | 766/1000 [05:38<01:20,  2.90it/s]

(38, 3)


 77%|█████████████████████████████▉         | 767/1000 [05:38<01:28,  2.63it/s]

(36, 3)


 77%|█████████████████████████████▉         | 768/1000 [05:39<01:20,  2.88it/s]

(38, 3)


 77%|█████████████████████████████▉         | 769/1000 [05:39<01:13,  3.13it/s]

(39, 3)


 77%|██████████████████████████████         | 770/1000 [05:39<01:08,  3.38it/s]

(38, 3)


 77%|██████████████████████████████         | 771/1000 [05:40<01:55,  1.99it/s]

(48, 3)


 77%|██████████████████████████████         | 772/1000 [05:40<01:37,  2.35it/s]

(36, 3)


 77%|██████████████████████████████▏        | 773/1000 [05:41<01:24,  2.68it/s]

(38, 3)


 77%|██████████████████████████████▏        | 774/1000 [05:41<01:49,  2.07it/s]

(41, 3)


 78%|██████████████████████████████▏        | 775/1000 [05:42<01:32,  2.42it/s]

(38, 3)


 78%|██████████████████████████████▎        | 776/1000 [05:42<01:23,  2.69it/s]

(38, 3)


 78%|██████████████████████████████▎        | 777/1000 [05:42<01:23,  2.67it/s]

(42, 3)


 78%|██████████████████████████████▎        | 778/1000 [05:43<01:26,  2.56it/s]

(39, 3)


 78%|██████████████████████████████▍        | 779/1000 [05:43<01:30,  2.44it/s]

(38, 3)


 78%|██████████████████████████████▍        | 780/1000 [05:43<01:26,  2.54it/s]

(40, 3)


 78%|██████████████████████████████▍        | 781/1000 [05:44<01:29,  2.45it/s]

(40, 3)


 78%|██████████████████████████████▍        | 782/1000 [05:44<01:21,  2.67it/s]

(39, 3)


 78%|██████████████████████████████▌        | 783/1000 [05:45<01:41,  2.14it/s]

(38, 3)


 78%|██████████████████████████████▌        | 784/1000 [05:45<01:40,  2.15it/s]

(40, 3)


 78%|██████████████████████████████▌        | 785/1000 [05:47<02:26,  1.47it/s]

(40, 3)


 79%|██████████████████████████████▋        | 786/1000 [05:47<01:59,  1.79it/s]

(39, 3)


 79%|██████████████████████████████▋        | 787/1000 [05:47<01:50,  1.92it/s]

(41, 3)


 79%|██████████████████████████████▋        | 788/1000 [05:48<01:46,  1.99it/s]

(39, 3)


 79%|██████████████████████████████▊        | 789/1000 [05:48<01:48,  1.94it/s]

(38, 3)


 79%|██████████████████████████████▊        | 790/1000 [05:49<01:32,  2.26it/s]

(37, 3)


 79%|██████████████████████████████▊        | 791/1000 [05:49<01:24,  2.47it/s]

(41, 3)


 79%|██████████████████████████████▉        | 792/1000 [05:49<01:28,  2.36it/s]

(41, 3)


 79%|██████████████████████████████▉        | 793/1000 [05:50<01:30,  2.29it/s]

(41, 3)


 79%|██████████████████████████████▉        | 794/1000 [05:50<01:30,  2.28it/s]

(40, 3)


 80%|███████████████████████████████        | 795/1000 [05:51<01:29,  2.30it/s]

(39, 3)


 80%|███████████████████████████████        | 796/1000 [05:51<01:20,  2.54it/s]

(41, 3)


 80%|███████████████████████████████        | 797/1000 [05:51<01:16,  2.66it/s]

(40, 3)


 80%|███████████████████████████████        | 798/1000 [05:52<01:09,  2.91it/s]

(40, 3)


 80%|███████████████████████████████▏       | 799/1000 [05:52<01:02,  3.21it/s]

(35, 3)


 80%|███████████████████████████████▏       | 800/1000 [05:52<00:59,  3.33it/s]

(37, 3)


 80%|███████████████████████████████▏       | 801/1000 [05:52<00:58,  3.43it/s]

(41, 3)


 80%|███████████████████████████████▎       | 802/1000 [05:53<00:55,  3.56it/s]

(38, 3)


 80%|███████████████████████████████▎       | 803/1000 [05:53<00:58,  3.38it/s]

(35, 3)


 80%|███████████████████████████████▎       | 804/1000 [05:53<00:56,  3.44it/s]

(39, 3)


 80%|███████████████████████████████▍       | 805/1000 [05:53<00:54,  3.60it/s]

(37, 3)


 81%|███████████████████████████████▍       | 806/1000 [05:54<01:05,  2.96it/s]

(41, 3)


 81%|███████████████████████████████▍       | 807/1000 [05:54<01:03,  3.04it/s]

(40, 3)


 81%|███████████████████████████████▌       | 808/1000 [05:54<00:57,  3.33it/s]

(37, 3)


 81%|███████████████████████████████▌       | 809/1000 [05:56<01:49,  1.75it/s]

(39, 3)


 81%|███████████████████████████████▌       | 810/1000 [05:56<01:32,  2.05it/s]

(37, 3)


 81%|███████████████████████████████▋       | 811/1000 [05:56<01:18,  2.40it/s]

(37, 3)


 81%|███████████████████████████████▋       | 812/1000 [05:57<01:32,  2.03it/s]

(36, 3)


 81%|███████████████████████████████▋       | 813/1000 [05:57<01:20,  2.32it/s]

(37, 3)


 81%|███████████████████████████████▋       | 814/1000 [05:57<01:12,  2.55it/s]

(40, 3)


 82%|███████████████████████████████▊       | 815/1000 [05:58<01:02,  2.96it/s]

(37, 3)


 82%|███████████████████████████████▊       | 816/1000 [05:58<01:18,  2.34it/s]

(36, 3)


 82%|███████████████████████████████▊       | 817/1000 [05:59<01:18,  2.32it/s]

(36, 3)


 82%|███████████████████████████████▉       | 818/1000 [05:59<01:10,  2.58it/s]

(37, 3)


 82%|███████████████████████████████▉       | 819/1000 [05:59<01:02,  2.90it/s]

(36, 3)


 82%|███████████████████████████████▉       | 820/1000 [06:00<01:05,  2.75it/s]

(42, 3)


 82%|████████████████████████████████       | 821/1000 [06:00<01:03,  2.81it/s]

(41, 3)


 82%|████████████████████████████████       | 822/1000 [06:00<01:03,  2.81it/s]

(40, 3)


 82%|████████████████████████████████       | 823/1000 [06:01<01:18,  2.24it/s]

(35, 3)


 82%|████████████████████████████████▏      | 824/1000 [06:01<01:14,  2.37it/s]

(43, 3)


 82%|████████████████████████████████▏      | 825/1000 [06:02<01:33,  1.87it/s]

(39, 3)


 83%|████████████████████████████████▏      | 826/1000 [06:03<01:22,  2.12it/s]

(38, 3)


 83%|████████████████████████████████▎      | 827/1000 [06:03<01:46,  1.63it/s]

(38, 3)


 83%|████████████████████████████████▎      | 828/1000 [06:04<01:37,  1.76it/s]

(38, 3)


 83%|████████████████████████████████▎      | 829/1000 [06:04<01:37,  1.76it/s]

(39, 3)


 83%|████████████████████████████████▎      | 830/1000 [06:05<01:37,  1.74it/s]

(35, 3)


 83%|████████████████████████████████▍      | 831/1000 [06:06<01:37,  1.74it/s]

(40, 3)


 83%|████████████████████████████████▍      | 832/1000 [06:06<01:35,  1.75it/s]

(36, 3)


 83%|████████████████████████████████▍      | 833/1000 [06:07<01:24,  1.98it/s]

(42, 3)


 83%|████████████████████████████████▌      | 834/1000 [06:07<01:29,  1.86it/s]

(41, 3)


 84%|████████████████████████████████▌      | 835/1000 [06:08<01:20,  2.04it/s]

(40, 3)


 84%|████████████████████████████████▌      | 836/1000 [06:08<01:14,  2.20it/s]

(36, 3)


 84%|████████████████████████████████▋      | 837/1000 [06:08<01:06,  2.44it/s]

(41, 3)


 84%|████████████████████████████████▋      | 838/1000 [06:09<00:59,  2.71it/s]

(39, 3)


 84%|████████████████████████████████▋      | 839/1000 [06:09<00:58,  2.74it/s]

(41, 3)


 84%|████████████████████████████████▊      | 840/1000 [06:10<01:11,  2.23it/s]

(34, 3)


 84%|████████████████████████████████▊      | 841/1000 [06:10<01:07,  2.37it/s]

(39, 3)


 84%|████████████████████████████████▊      | 842/1000 [06:10<01:07,  2.34it/s]

(49, 3)


 84%|████████████████████████████████▉      | 843/1000 [06:11<01:03,  2.47it/s]

(44, 3)


 84%|████████████████████████████████▉      | 844/1000 [06:11<00:59,  2.62it/s]

(39, 3)


 84%|████████████████████████████████▉      | 845/1000 [06:11<00:56,  2.76it/s]

(42, 3)


 85%|████████████████████████████████▉      | 846/1000 [06:12<00:58,  2.62it/s]

(44, 3)


 85%|█████████████████████████████████      | 847/1000 [06:12<01:03,  2.43it/s]

(43, 3)


 85%|█████████████████████████████████      | 848/1000 [06:13<00:57,  2.65it/s]

(38, 3)


 85%|█████████████████████████████████      | 849/1000 [06:13<01:09,  2.18it/s]

(41, 3)


 85%|█████████████████████████████████▏     | 850/1000 [06:13<01:00,  2.48it/s]

(39, 3)


 85%|█████████████████████████████████▏     | 851/1000 [06:14<00:54,  2.73it/s]

(39, 3)


 85%|█████████████████████████████████▏     | 852/1000 [06:14<00:50,  2.95it/s]

(35, 3)


 85%|█████████████████████████████████▎     | 853/1000 [06:14<00:49,  2.99it/s]

(39, 3)


 85%|█████████████████████████████████▎     | 854/1000 [06:15<00:50,  2.90it/s]

(36, 3)


 86%|█████████████████████████████████▎     | 855/1000 [06:15<00:52,  2.74it/s]

(40, 3)


 86%|█████████████████████████████████▍     | 856/1000 [06:15<00:51,  2.80it/s]

(40, 3)


 86%|█████████████████████████████████▍     | 857/1000 [06:16<00:56,  2.52it/s]

(41, 3)


 86%|█████████████████████████████████▍     | 858/1000 [06:16<00:49,  2.86it/s]

(38, 3)


 86%|█████████████████████████████████▌     | 859/1000 [06:16<00:46,  3.03it/s]

(36, 3)


 86%|█████████████████████████████████▌     | 860/1000 [06:17<00:43,  3.19it/s]

(41, 3)


 86%|█████████████████████████████████▌     | 861/1000 [06:17<01:02,  2.21it/s]

(43, 3)


 86%|█████████████████████████████████▌     | 862/1000 [06:18<01:04,  2.14it/s]

(38, 3)


 86%|█████████████████████████████████▋     | 863/1000 [06:18<00:58,  2.34it/s]

(39, 3)


 86%|█████████████████████████████████▋     | 864/1000 [06:19<00:50,  2.68it/s]

(41, 3)


 86%|█████████████████████████████████▋     | 865/1000 [06:19<00:48,  2.78it/s]

(36, 3)


 87%|█████████████████████████████████▊     | 866/1000 [06:19<00:48,  2.79it/s]

(39, 3)


 87%|█████████████████████████████████▊     | 867/1000 [06:20<00:46,  2.88it/s]

(39, 3)


 87%|█████████████████████████████████▊     | 868/1000 [06:21<01:21,  1.62it/s]

(41, 3)


 87%|█████████████████████████████████▉     | 869/1000 [06:21<01:08,  1.93it/s]

(41, 3)


 87%|█████████████████████████████████▉     | 870/1000 [06:22<01:16,  1.71it/s]

(44, 3)


 87%|█████████████████████████████████▉     | 871/1000 [06:22<01:02,  2.08it/s]

(37, 3)


 87%|██████████████████████████████████     | 873/1000 [06:23<00:44,  2.88it/s]

(39, 3)
(39, 3)


 87%|██████████████████████████████████     | 874/1000 [06:23<00:38,  3.24it/s]

(36, 3)


 88%|██████████████████████████████████▏    | 875/1000 [06:23<00:38,  3.21it/s]

(39, 3)


 88%|██████████████████████████████████▏    | 876/1000 [06:23<00:37,  3.33it/s]

(40, 3)


 88%|██████████████████████████████████▏    | 877/1000 [06:24<00:35,  3.49it/s]

(40, 3)


 88%|██████████████████████████████████▏    | 878/1000 [06:24<00:35,  3.48it/s]

(41, 3)


 88%|██████████████████████████████████▎    | 879/1000 [06:24<00:34,  3.53it/s]

(39, 3)


 88%|██████████████████████████████████▎    | 880/1000 [06:25<00:35,  3.41it/s]

(35, 3)


 88%|██████████████████████████████████▎    | 881/1000 [06:25<00:35,  3.35it/s]

(40, 3)


 88%|██████████████████████████████████▍    | 882/1000 [06:25<00:33,  3.48it/s]

(39, 3)


 88%|██████████████████████████████████▍    | 884/1000 [06:26<00:30,  3.77it/s]

(41, 3)
(40, 3)


 88%|██████████████████████████████████▌    | 885/1000 [06:26<00:29,  3.96it/s]

(36, 3)


 89%|██████████████████████████████████▌    | 886/1000 [06:26<00:27,  4.09it/s]

(37, 3)


 89%|██████████████████████████████████▋    | 888/1000 [06:27<00:35,  3.14it/s]

(45, 3)
(34, 3)


 89%|██████████████████████████████████▋    | 889/1000 [06:27<00:37,  2.99it/s]

(38, 3)


 89%|██████████████████████████████████▋    | 890/1000 [06:28<00:34,  3.23it/s]

(39, 3)


 89%|██████████████████████████████████▋    | 891/1000 [06:28<00:52,  2.08it/s]

(42, 3)


 89%|██████████████████████████████████▊    | 892/1000 [06:29<00:55,  1.93it/s]

(39, 3)


 89%|██████████████████████████████████▊    | 893/1000 [06:30<01:02,  1.72it/s]

(41, 3)


 89%|██████████████████████████████████▊    | 894/1000 [06:30<00:50,  2.10it/s]

(36, 3)


 90%|██████████████████████████████████▉    | 895/1000 [06:30<00:41,  2.51it/s]

(35, 3)


 90%|██████████████████████████████████▉    | 896/1000 [06:30<00:36,  2.87it/s]

(35, 3)


 90%|██████████████████████████████████▉    | 897/1000 [06:31<00:41,  2.51it/s]

(41, 3)


 90%|███████████████████████████████████    | 898/1000 [06:32<00:52,  1.94it/s]

(42, 3)


 90%|███████████████████████████████████    | 899/1000 [06:32<00:51,  1.97it/s]

(37, 3)


 90%|███████████████████████████████████    | 900/1000 [06:32<00:43,  2.30it/s]

(39, 3)


 90%|███████████████████████████████████▏   | 901/1000 [06:33<00:37,  2.66it/s]

(36, 3)


 90%|███████████████████████████████████▏   | 902/1000 [06:33<00:45,  2.17it/s]

(43, 3)


 90%|███████████████████████████████████▏   | 903/1000 [06:34<00:37,  2.57it/s]

(35, 3)


 90%|███████████████████████████████████▎   | 905/1000 [06:34<00:30,  3.11it/s]

(41, 3)
(35, 3)


 91%|███████████████████████████████████▎   | 906/1000 [06:34<00:31,  3.03it/s]

(36, 3)


 91%|███████████████████████████████████▎   | 907/1000 [06:35<00:29,  3.17it/s]

(38, 3)


 91%|███████████████████████████████████▍   | 908/1000 [06:35<00:27,  3.29it/s]

(40, 3)


 91%|███████████████████████████████████▍   | 909/1000 [06:35<00:31,  2.91it/s]

(36, 3)


 91%|███████████████████████████████████▍   | 910/1000 [06:36<00:34,  2.60it/s]

(38, 3)


 91%|███████████████████████████████████▌   | 911/1000 [06:36<00:30,  2.92it/s]

(37, 3)


 91%|███████████████████████████████████▌   | 912/1000 [06:36<00:27,  3.19it/s]

(41, 3)


 91%|███████████████████████████████████▌   | 913/1000 [06:37<00:25,  3.41it/s]

(40, 3)


 91%|███████████████████████████████████▋   | 914/1000 [06:38<00:44,  1.92it/s]

(37, 3)


 92%|███████████████████████████████████▋   | 915/1000 [06:38<00:45,  1.85it/s]

(37, 3)


 92%|███████████████████████████████████▊   | 917/1000 [06:39<00:31,  2.67it/s]

(37, 3)
(36, 3)


 92%|███████████████████████████████████▊   | 918/1000 [06:39<00:31,  2.58it/s]

(42, 3)


 92%|███████████████████████████████████▊   | 919/1000 [06:40<00:30,  2.65it/s]

(37, 3)


 92%|███████████████████████████████████▉   | 920/1000 [06:40<00:31,  2.51it/s]

(42, 3)


 92%|███████████████████████████████████▉   | 922/1000 [06:40<00:24,  3.16it/s]

(36, 3)
(33, 3)


 92%|███████████████████████████████████▉   | 923/1000 [06:41<00:21,  3.51it/s]

(33, 3)


 92%|████████████████████████████████████   | 924/1000 [06:41<00:22,  3.45it/s]

(42, 3)


 92%|████████████████████████████████████   | 925/1000 [06:42<00:27,  2.77it/s]

(38, 3)


 93%|████████████████████████████████████   | 926/1000 [06:42<00:31,  2.33it/s]

(44, 3)


 93%|████████████████████████████████████▏  | 927/1000 [06:42<00:29,  2.46it/s]

(42, 3)


 93%|████████████████████████████████████▏  | 928/1000 [06:43<00:26,  2.68it/s]

(38, 3)


 93%|████████████████████████████████████▏  | 929/1000 [06:44<00:38,  1.87it/s]

(37, 3)


 93%|████████████████████████████████████▎  | 930/1000 [06:44<00:41,  1.68it/s]

(37, 3)


 93%|████████████████████████████████████▎  | 931/1000 [06:45<00:35,  1.96it/s]

(40, 3)


 93%|████████████████████████████████████▎  | 932/1000 [06:45<00:31,  2.19it/s]

(34, 3)


 93%|████████████████████████████████████▍  | 933/1000 [06:45<00:27,  2.44it/s]

(36, 3)


 93%|████████████████████████████████████▍  | 934/1000 [06:46<00:24,  2.70it/s]

(36, 3)


 94%|████████████████████████████████████▍  | 935/1000 [06:46<00:23,  2.72it/s]

(43, 3)


 94%|████████████████████████████████████▌  | 936/1000 [06:46<00:22,  2.79it/s]

(45, 3)


 94%|████████████████████████████████████▌  | 937/1000 [06:47<00:22,  2.82it/s]

(38, 3)


 94%|████████████████████████████████████▌  | 938/1000 [06:47<00:20,  2.97it/s]

(37, 3)


 94%|████████████████████████████████████▌  | 939/1000 [06:47<00:22,  2.72it/s]

(39, 3)


 94%|████████████████████████████████████▋  | 940/1000 [06:48<00:26,  2.25it/s]

(38, 3)


 94%|████████████████████████████████████▋  | 941/1000 [06:49<00:28,  2.06it/s]

(37, 3)


 94%|████████████████████████████████████▋  | 942/1000 [06:49<00:25,  2.30it/s]

(39, 3)


 94%|████████████████████████████████████▊  | 943/1000 [06:49<00:22,  2.52it/s]

(39, 3)


 94%|████████████████████████████████████▊  | 944/1000 [06:50<00:24,  2.32it/s]

(42, 3)


 94%|████████████████████████████████████▊  | 945/1000 [06:50<00:21,  2.53it/s]

(38, 3)


 95%|████████████████████████████████████▉  | 946/1000 [06:50<00:20,  2.67it/s]

(41, 3)


 95%|████████████████████████████████████▉  | 947/1000 [06:51<00:23,  2.25it/s]

(43, 3)


 95%|████████████████████████████████████▉  | 948/1000 [06:52<00:30,  1.73it/s]

(45, 3)


 95%|█████████████████████████████████████  | 949/1000 [06:53<00:33,  1.53it/s]

(41, 3)


 95%|█████████████████████████████████████  | 950/1000 [06:53<00:30,  1.66it/s]

(38, 3)


 95%|█████████████████████████████████████  | 951/1000 [06:54<00:26,  1.84it/s]

(36, 3)


 95%|█████████████████████████████████████▏ | 952/1000 [06:54<00:22,  2.15it/s]

(38, 3)


 95%|█████████████████████████████████████▏ | 953/1000 [06:54<00:22,  2.09it/s]

(38, 3)


 95%|█████████████████████████████████████▏ | 954/1000 [06:55<00:19,  2.39it/s]

(37, 3)


 96%|█████████████████████████████████████▏ | 955/1000 [06:55<00:16,  2.67it/s]

(40, 3)


 96%|█████████████████████████████████████▎ | 956/1000 [06:55<00:16,  2.60it/s]

(38, 3)


 96%|█████████████████████████████████████▎ | 957/1000 [06:56<00:15,  2.79it/s]

(40, 3)


 96%|█████████████████████████████████████▎ | 958/1000 [06:56<00:15,  2.72it/s]

(44, 3)


 96%|█████████████████████████████████████▍ | 959/1000 [06:57<00:21,  1.94it/s]

(38, 3)


 96%|█████████████████████████████████████▍ | 960/1000 [06:57<00:19,  2.07it/s]

(37, 3)


 96%|█████████████████████████████████████▍ | 961/1000 [06:58<00:18,  2.07it/s]

(40, 3)


 96%|█████████████████████████████████████▌ | 962/1000 [06:58<00:17,  2.21it/s]

(36, 3)


 96%|█████████████████████████████████████▌ | 963/1000 [06:58<00:14,  2.52it/s]

(37, 3)


 96%|█████████████████████████████████████▌ | 964/1000 [06:59<00:17,  2.11it/s]

(41, 3)


 96%|█████████████████████████████████████▋ | 965/1000 [07:00<00:18,  1.94it/s]

(38, 3)


 97%|█████████████████████████████████████▋ | 966/1000 [07:00<00:19,  1.73it/s]

(38, 3)


 97%|█████████████████████████████████████▋ | 967/1000 [07:01<00:15,  2.09it/s]

(38, 3)


 97%|█████████████████████████████████████▊ | 968/1000 [07:01<00:14,  2.26it/s]

(39, 3)


 97%|█████████████████████████████████████▊ | 969/1000 [07:01<00:13,  2.36it/s]

(43, 3)


 97%|█████████████████████████████████████▊ | 970/1000 [07:02<00:12,  2.48it/s]

(43, 3)


 97%|█████████████████████████████████████▊ | 971/1000 [07:02<00:10,  2.76it/s]

(37, 3)


 97%|█████████████████████████████████████▉ | 972/1000 [07:02<00:09,  2.87it/s]

(46, 3)


 97%|█████████████████████████████████████▉ | 973/1000 [07:03<00:09,  2.85it/s]

(44, 3)


 97%|█████████████████████████████████████▉ | 974/1000 [07:03<00:08,  2.95it/s]

(44, 3)


 98%|██████████████████████████████████████ | 975/1000 [07:03<00:09,  2.75it/s]

(39, 3)


 98%|██████████████████████████████████████ | 976/1000 [07:04<00:12,  1.92it/s]

(43, 3)


 98%|██████████████████████████████████████ | 977/1000 [07:05<00:10,  2.20it/s]

(40, 3)


 98%|██████████████████████████████████████▏| 978/1000 [07:05<00:09,  2.33it/s]

(42, 3)


 98%|██████████████████████████████████████▏| 979/1000 [07:05<00:08,  2.61it/s]

(39, 3)


 98%|██████████████████████████████████████▏| 980/1000 [07:07<00:13,  1.51it/s]

(43, 3)


 98%|██████████████████████████████████████▎| 981/1000 [07:08<00:14,  1.29it/s]

(42, 3)


 98%|██████████████████████████████████████▎| 982/1000 [07:08<00:12,  1.40it/s]

(40, 3)


 98%|██████████████████████████████████████▎| 983/1000 [07:08<00:09,  1.75it/s]

(35, 3)


 98%|██████████████████████████████████████▍| 984/1000 [07:09<00:07,  2.07it/s]

(41, 3)


 98%|██████████████████████████████████████▍| 985/1000 [07:09<00:07,  2.08it/s]

(36, 3)


 99%|██████████████████████████████████████▍| 986/1000 [07:10<00:06,  2.16it/s]

(35, 3)


 99%|██████████████████████████████████████▌| 988/1000 [07:10<00:03,  3.02it/s]

(35, 3)
(36, 3)


 99%|██████████████████████████████████████▌| 989/1000 [07:10<00:03,  2.89it/s]

(47, 3)


 99%|██████████████████████████████████████▌| 990/1000 [07:11<00:03,  2.61it/s]

(42, 3)


 99%|██████████████████████████████████████▋| 991/1000 [07:11<00:03,  2.84it/s]

(40, 3)


 99%|██████████████████████████████████████▋| 992/1000 [07:11<00:02,  3.11it/s]

(40, 3)


 99%|██████████████████████████████████████▋| 993/1000 [07:12<00:02,  2.45it/s]

(41, 3)


 99%|██████████████████████████████████████▊| 994/1000 [07:12<00:02,  2.64it/s]

(41, 3)


100%|██████████████████████████████████████▊| 995/1000 [07:13<00:01,  2.68it/s]

(43, 3)


100%|██████████████████████████████████████▊| 996/1000 [07:13<00:01,  2.76it/s]

(42, 3)


100%|██████████████████████████████████████▉| 997/1000 [07:13<00:01,  2.86it/s]

(35, 3)


100%|██████████████████████████████████████▉| 998/1000 [07:14<00:00,  2.68it/s]

(40, 3)


100%|██████████████████████████████████████▉| 999/1000 [07:14<00:00,  2.86it/s]

(39, 3)


100%|██████████████████████████████████████| 1000/1000 [07:14<00:00,  2.30it/s]

(40, 3)
CPU times: user 7min 15s, sys: 515 ms, total: 7min 16s
Wall time: 7min 14s


In [20]:
from skfp.fingerprints import E3FPFingerprint
from skfp.preprocessing import MolFromSmilesTransformer, ConformerGenerator

In [21]:
%%time

conf_gen = ConformerGenerator()
mols = conf_gen.transform(mols)

CPU times: user 4min 13s, sys: 61.2 ms, total: 4min 14s
Wall time: 4min 14s


# Conforce

In [7]:
import sys
import CDPL.Chem as CDPLChem
import CDPL.ConfGen as ConfGen
import py3Dmol

# dictionary mapping status codes to human readable strings
STATUS_TO_STR = {
    ConfGen.ReturnCode.UNINITIALIZED: 'uninitialized',
    ConfGen.ReturnCode.TIMEOUT: 'max. processing time exceeded',
    ConfGen.ReturnCode.ABORTED: 'aborted',
    ConfGen.ReturnCode.FORCEFIELD_SETUP_FAILED: 'force field setup failed',
    ConfGen.ReturnCode.FORCEFIELD_MINIMIZATION_FAILED: 'force field structure refinement failed',
    ConfGen.ReturnCode.FRAGMENT_LIBRARY_NOT_SET: 'fragment library not available',
    ConfGen.ReturnCode.FRAGMENT_CONF_GEN_FAILED: 'fragment conformer generation failed',
    ConfGen.ReturnCode.FRAGMENT_CONF_GEN_TIMEOUT: 'fragment conformer generation timeout',
    ConfGen.ReturnCode.FRAGMENT_ALREADY_PROCESSED: 'fragment already processed',
    ConfGen.ReturnCode.TORSION_DRIVING_FAILED: 'torsion driving failed',
    ConfGen.ReturnCode.CONF_GEN_FAILED: 'conformer generation failed'
}


def gen3DStructure(smiles, struct_gen) -> int:
    smiles = normalize_smiles(
         smiles,
         canonical=True,
         do_random = False,
         isomeric=True,
         kekulize = False,
         replace_dy=True,
         return_mol=False)
    mol = CDPLChem.parseSMILES(smiles)
    # prepare the molecule for 3D structure generation
    ConfGen.prepareForConformerGeneration(mol)

    # generate the 3D structure
    status = struct_gen.generate(mol)

    # if successful, store the generated conformer ensemble as
    # per atom 3D coordinates arrays (= the way conformers are represented in CDPKit)

    if status == ConfGen.ReturnCode.SUCCESS:
        struct_gen.setCoordinates(mol)
        # enforce the output of 3D coordinates in case of MDL file formats
#         Chem.setMDLDimensionality(mol, 3)
    else:
        print(f'Error: 3D structure generation for molecule {smiles} failed: {STATUS_TO_STR[status]}')

    # return status code
    return status, mol

In [8]:
SDF_PATH = '/home/dangnh36/datasets/competitions/leash_belka/processed/features/3d_mols.sdf'

struct_gen = ConfGen.StructureGenerator()
struct_gen.settings.timeout = 3600 * 1000  # apply the -t argument

writer = CDPLChem.MolecularGraphWriter(SDF_PATH)

In [9]:
for i in tqdm(range(100)):
    smiles = train_df[i, 'molecule']
    status, mol = gen3DStructure(smiles, struct_gen)
    if not writer.write(mol):
        print(f'Error: writing 3D structure of molecule failed:\n{smiles}')
    # output the generated 3D structure
    # if not writer.write(mol):
    #     sys.exit('Error: writing 3D structure of molecule %s failed' % mol_id)

 31%|████████████▋                            | 31/100 [00:06<00:24,  2.81it/s]

Error: 3D structure generation for molecule C#CCOc1ccc(CNc2nc(Nc3ccc(B4OC(C)(C)C(C)(C)O4)cc3)nc(N[C@@H](CC#C)CC(=O)NC)n2)cc1 failed: force field setup failed


100%|████████████████████████████████████████| 100/100 [00:16<00:00,  5.99it/s]


In [30]:
#visualization
rd_mols = Chem.SDMolSupplier(SDF_PATH, removeHs=False, sanitize=False)

p = py3Dmol.view(width=1200, height=400, viewergrid=(1,3))
#
for j,t in enumerate([10, 20, 30]):
    p.removeAllModels(viewer=(0,j))
    p.addModel(Chem.MolToMolBlock(rd_mols[t], confId=0), 'sdf', viewer=(0,j))
    p.setStyle({'stick':{}}, viewer=(0,j))
p.zoomTo()
p.show()

3Dmol.js failed to load for some reason. Please check your browser console for error messages.

In [28]:
#visualization
rd_mols = Chem.SDMolSupplier(SDF_PATH)

p = py3Dmol.view(width=1200, height=400, viewergrid=(1,3))
#
for j,t in enumerate([10, 20, 30]):
    p.removeAllModels(viewer=(0,j))
    p.addModel(Chem.MolToMolBlock(rd_mols[t], confId=0), 'sdf', viewer=(0,j))
    p.setStyle({'stick':{}}, viewer=(0,j))
p.zoomTo()
p.show()

3Dmol.js failed to load for some reason. Please check your browser console for error messages.

In [31]:
cdpl_mols = Chem.SDMolSupplier(SDF_PATH, removeHs=False, sanitize=False)


for i in range(1):
    cdpl_mol = cdpl_mols[i]
    cdpl_num_atoms = cdpl_mol.GetNumAtoms()
    cdpl_pos = cdpl_mols.GetItemText(i).split('\n')[4:4 + cdpl_num_atoms]
    cdpl_pos = np.array([[float(x) for x in line.split()[:3]] for line in cdpl_pos], dtype=np.float32)
    
    rd_mol = rd_mols[i]
    rd_pos = rd_mol.GetConformer().GetPositions()
#     assert sum(cdpl_pos - rd_pos) == 0
    print(cdpl_num_atoms, rd_mol.GetNumAtoms(), mols[i].GetNumAtoms())
    print(cdpl_pos, rd_pos, sep = '\n\n\n')

75 75 41
[[-9.34900e-01 -1.10000e-03  2.49600e+00]
 [-5.13700e-01  0.00000e+00  1.37200e+00]
 [ 0.00000e+00  0.00000e+00  0.00000e+00]
 [ 1.41800e+00 -0.00000e+00  0.00000e+00]
 [ 2.04770e+00 -0.00000e+00 -1.22340e+00]
 [ 1.30380e+00 -0.00000e+00 -2.40610e+00]
 [ 1.93850e+00  1.00000e-03 -3.65710e+00]
 [ 3.33660e+00 -9.00000e-04 -3.77890e+00]
 [ 4.01650e+00 -4.00000e-04 -5.10020e+00]
 [ 5.04440e+00 -1.00420e+00 -5.26320e+00]
 [ 4.81640e+00 -2.35020e+00 -5.56480e+00]
 [ 5.87160e+00 -3.17590e+00 -5.68810e+00]
 [ 5.58190e+00 -4.45180e+00 -5.98570e+00]
 [ 6.65200e+00 -5.33930e+00 -6.13230e+00]
 [ 6.53240e+00 -6.74480e+00 -6.45070e+00]
 [ 7.87980e+00 -7.41640e+00 -6.53600e+00]
 [ 8.65900e+00 -7.32510e+00 -5.21740e+00]
 [ 8.22960e+00 -8.57440e+00 -4.46200e+00]
 [ 8.11810e+00 -9.62030e+00 -5.56600e+00]
 [ 7.72080e+00 -8.85590e+00 -6.74100e+00]
 [ 7.41340e+00 -9.44280e+00 -7.97210e+00]
 [ 7.26510e+00 -1.08162e+01 -8.15150e+00]
 [ 6.96250e+00 -1.13663e+01 -9.40500e+00]
 [ 6.83310e+00 -1.04544e+

In [13]:
# kaggle_mol[0].GetConformer().GetPositions()