In [1]:
import torch
from torch.nn import BCEWithLogitsLoss
import polars as pl
import numpy as np
from tqdm import tqdm
from rdkit.ML.Descriptors.MoleculeDescriptors import MolecularDescriptorCalculator
from rdkit.Chem import Descriptors
from math import log
import math

In [2]:
arr = torch.zeros((4, 9))
arr

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
arr[3, np.array([0, 1, 2, 0, 0, 0, 5], dtype = np.uint8).tolist()] = 3
arr

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [3., 3., 3., 0., 0., 3., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [3., 3., 3., 0., 0., 3., 0., 0., 0.]])

In [ ]:
parameters = DNP.desc_norm_params.items()

In [30]:
691 + 181

872

In [35]:
271*((181*693) + (691*692/2))

98784649.0

In [36]:
271 * 693 * 181 + 271 * (691 * 690 / 2 + 691)

98784649.0

In [37]:
271 + 872

1143

In [38]:
36 + 377 + 446

859

In [51]:
98_000_000 / 271

361623.6162361624

In [50]:
(181*693) + (691*692/2)

364519.0

In [57]:
# BB1 appear
train_bb1 = (181*693) + (691*692/2) # 364519
train_bb23_691 = (271 * 181 + 271 * 690 / 2 + 271 ) + (271 * 690 / 2) # 236312
train_bb23_2 = 271 * 181 # 49051
train_bb23_181 = 271 * 693 # 187803

In [ ]:
test_bb1 = 377 * 446 # 168142
test_bb2 = 36 * 446 # 16056
test_bb3 = 36 * 377 # 13572

In [81]:
idxs = np.array([0, 10, 20, 30])

In [82]:
np.where(idxs < 15)[0]

array([0, 1])

In [84]:
arr = np.array([[1,2,3], [4,5,6], [7, 8, 9], [10, 11, 12]])
div = np.array([2,2,4])
arr/div

array([[0.5 , 1.  , 0.75],
       [2.  , 2.5 , 1.5 ],
       [3.5 , 4.  , 2.25],
       [5.  , 5.5 , 3.  ]])

In [78]:
486390 * 25

12159750

In [62]:
364519 / 168142

2.1679235408166906

In [ ]:
17, 36, 36

In [65]:
17 * 36 * 36 / 2 / 17

648.0

In [64]:
36 * 36, 17 * 36 * 2

(1296, 1224)

In [66]:
364519 / 1296

281.26466049382714

In [77]:
11322 * 250

2830500

In [69]:
36 * 377*446

6053112

In [70]:
6053112 / 486390

12.444976253623635

In [71]:
12.444976253623635 * 2.1679235408166906

26.97975698513538

In [ ]:
271 * 181 + 271 * ()

In [ ]:
364519, 361623

In [46]:
693 * 872, 77 * 872, 77 * 693

(604296, 67144, 53361)

In [47]:
377 * 446, 36 * 446, 36 * 377

(168142, 16056, 13572)

In [49]:
604296 / 168142, 67144 / 16056, 53361 / 13572

(3.593962246196667, 4.181863477827603, 3.9316976127320955)

In [ ]:
271 * (691 + 2) * (691 + 181)

17x((2x34)+(34x35/2))

17x(36x37/2)

36x377x446

In [41]:
(36 * 377 * 446) / (271 * 872)

25.61491587392938

In [27]:
36 * 377 * 446

6053112

In [42]:
36 * 377 * 446 / 500_000

12.106224

In [24]:
def log2(n):
    return log(n, 2)

In [33]:
271 * 693 * 872 / 2

81882108.0

In [29]:
log2(271) + log2(693) + log2(691 + 181)

27.287044908268015

In [28]:
log2(36) + log2(377) + log2(446)

22.529245614631282

(0.0036900369003690036, 0.001443001443001443, 0.0011467889908256881)

In [ ]:
1/36, 1/377, 1/446

In [15]:
len(Descriptors._descList)

210

In [ ]:
MolecularDescriptorCalculator.

In [12]:
n = 81542164.0
arr1 = np.array([n], np.float32)
for i in range(-10, 10, 1):
    arr2 = np.array([n + i], dtype = np.float32)
    print(i, arr1 == arr2 )

-10 [False]
-9 [False]
-8 [ True]
-7 [ True]
-6 [ True]
-5 [ True]
-4 [ True]
-3 [ True]
-2 [ True]
-1 [ True]
0 [ True]
1 [False]
2 [False]
3 [False]
4 [False]
5 [False]
6 [False]
7 [False]
8 [False]
9 [False]


In [ ]:
li = [81542164, 48869979]

arr = torch.Tensor(li)
arr = torch.tensor(li, dtype = torch.float32)
# equivalent to 

arr2 = torch.from_numpy(np.array(li))
print('[0]', arr, arr2)
print('[1]', arr.dtype, arr2.dtype)
print('[2]', arr.type(torch.int64) == arr2, arr == arr2.float())
print('[3]', arr2 - arr, arr - arr2)
print('[4]', arr2==arr, arr == arr2)
print('[5]', arr.type(torch.int64) == arr2, arr == arr2.float())
print('-----[6]----', arr.cpu().numpy() == arr2.cpu().numpy(), arr2.cpu().numpy() == arr.cpu().numpy())
print('[7]', arr.numpy().dtype, arr2.numpy().dtype)
print('[8]', arr.numpy().astype('int64') == arr2.numpy(), arr.numpy() == arr2.numpy().astype('float32'))

In [4]:
li = [81542164, 48869979]

arr = torch.tensor(li, dtype = torch.float32)
# arr = torch.Tensor(li)

arr2 = torch.from_numpy(np.array(li))
print('[0]', arr, arr2)
print('[1]', arr.dtype, arr2.dtype)
print('[2]', arr2 - arr, arr - arr2)
print('[3]', arr.type(torch.int64) == arr2, arr == arr2.float())
print('[4]', arr2==arr, arr == arr2)
print('[5]', arr.cpu().numpy() == arr2.cpu().numpy(), arr2.cpu().numpy() == arr.cpu().numpy())

[0] tensor([81542160., 48869980.]) tensor([81542164, 48869979])
[1] torch.float32 torch.int64
[2] tensor([0., 0.]) tensor([0., 0.])
[3] tensor([False, False]) tensor([True, True])
[4] tensor([True, True]) tensor([True, True])
[5] [False False] [False False]


In [ ]:
df = pl.scan_csv('/home/dangnh36/datasets/competitions/leash_belka/processed/cv/16_19_0_2/train.csv').select(pl.col(
                                    'index')).collect()
df

In [ ]:
df.select(pl.n_unique('index'))

In [ ]:
arr = df.to_numpy()[:, 0]
arr.shape

In [ ]:
84053897 / 2

In [ ]:
arr1 = np.random.choice(arr, 42026948, replace=False)
arr1.shape

In [ ]:
arr2 = np.random.choice(arr, 42026948, replace=False)
arr2.shape

In [ ]:
len(set(arr1.tolist() + arr2.tolist()))

In [ ]:
84053897 - 63042196

In [ ]:
sampler = None

class Dataset:
    def __len__(self):
        return 84053897

dataset = Dataset()

from torch.utils.data import BatchSampler, RandomSampler, SequentialSampler
if sampler is None:
    # default behavior of torch.utils.data.DataLoader
    sampler = RandomSampler(dataset,
                            replacement=False,
                            num_samples=None,
                            generator=None)
# dataset's __getitem__(self, idxs) where idxs is a list of indices
# this may speedup when e.g tokenizer a batch of strings
# instead of tokenize each idividual string then collate to a batch
sampler = BatchSampler(sampler, 4096, True)
sampler

In [ ]:
all_idxs = []
all_idxs2 = []
for i, idxs in tqdm(enumerate(sampler)):
    print(type(idxs), type(idxs[0]))
    break
    assert len(idxs) == 4096, f'{len(idxs)}'
    all_idxs.extend(torch.Tensor(idxs).cpu().numpy())
    all_idxs2.extend(idxs)


In [ ]:
print(len(all_idxs))

In [ ]:
print(len(set(all_idxs)))

In [ ]:
print(len(set(all_idxs2)))

In [ ]:
all_idxs[:10]

In [ ]:
type(all_idxs[0])

In [ ]:
all_idxs2[:10]

In [ ]:
for i in range(len(all_idxs)):
    if all_idxs[i] != all_idxs2[i]:
        print(all_idxs[i], all_idxs2[i])

In [ ]:
torch.Tensor(idxs).cpu().numpy()

In [ ]:
torch.Tensor(idxs).cpu().numpy()

In [ ]:
len(set([int(e) for e in all_idxs]))

In [ ]:
all_idxs[:10]

In [ ]:
all_idxs2[:10]

In [ ]:
type(all_idxs[0]), type(all_idxs2[0])

In [ ]:
mask = torch.Tensor(
[
    [1, 1, 1, 0],
    [1, 0, 0, 0],
    [1, 1, 0, 0]
]
    
)
mask_pad = ( mask).long().bool().unsqueeze(1)
mask_pad = ( mask_pad.permute(0, 2,1) * mask_pad).unsqueeze(1)
print(mask_pad.shape)
mask_pad

In [ ]:
arr = torch.Tensor([[0, 0, 0], [0, 0, 0]]).long()
idxs = torch.Tensor([[0, 2], [1, 2]]).long()
# arr[idxs] = 1
for i, row in enumerate(idxs):
    arr[i, row] = 1
        
arr

In [ ]:
%%time
features = np.load('/home/dangnh36/datasets/competitions/leash_belka/processed/features/ecfp6/train.npy', mmap_mode='r')
# print(features.sum())
features.shape

In [ ]:
%%time

arr = np.unpackbits(features, axis = -1)
arr.shape

In [ ]:
pred = torch.Tensor([[12, -12, 0], [2, -4, -14], [3, 3, 3]]).float()
target = torch.Tensor([[1, 0, 0], [0, 0, 0], [1, 1, 0]]).float()

In [ ]:
mean = BCEWithLogitsLoss(reduction='mean')
sum = BCEWithLogitsLoss(reduction='sum')

In [ ]:
mean(pred, target) * 9

In [ ]:
sum(pred, target)

In [ ]:
df = pl.scan_csv('/home/dangnh36/datasets/competitions/leash_belka/processed/cv/v1/val.csv').collect()
df

In [ ]:
df[np.array([0, 1, 4]), 'subset'] = 11
df

In [ ]:
# idxs = np.concatenate(idxs)
# orders = np.argsort(idxs)
# preds = np.concatenate(preds)[orders]
# targets = np.concatenate(targets)[orders]

# # fill nan in preds
# nan_row_idxs = np.any(np.isnan(preds), axis=-1)
# num_nan = nan_row_idxs.sum()
# if num_nan > 0:
#     logger.warning("%d nan rows in prediction, set to 0", num_nan)
#     preds[nan_row_idxs, :] = 0
#     assert not np.any(np.isnan(preds))

# target_cols = ['BRD4', 'HSA', 'eSH']

In [ ]:
train_df = pl.scan_csv('/home/dangnh36/datasets/competitions/leash_belka/processed/train_v2.csv').select(
        pl.col('molecule'),
#         pl.col('bb1', 'bb2', 'bb3').cast(pl.UInt16),
        # pl.col('BRD4', 'HSA', 'sEH').cast(pl.UInt8),
    ).collect()
print(train_df.estimated_size('gb'), 'GB')
train_df

In [ ]:
help(Chem.MolToSmiles)

In [ ]:
from rdkit import Chem

def canonical_smiles(x):
    normalized = Chem.MolToSmiles(
        Chem.MolFromSmiles(x), canonical=True,
#         isomericSmiles=False
    )
    return normalized

In [ ]:
canonical_smiles(train_df[0, 'molecule'])

In [ ]:
for i in tqdm(range(1000_000)):
    mol = train_df[i, 'molecule']
    can = canonical_smiles(mol)
    assert mol == can, f'\n{mol}\n{can}'

In [ ]:
!cat /home/dangnh36/datasets/competitions/leash_belka/processed/features/maccs/README.md

In [ ]:
arr = np.memmap('/home/dangnh36/datasets/competitions/leash_belka/processed/features/maccs/train.mmap',
               dtype = np.uint8, shape = (98_415_610, 21))
arr.shape

In [ ]:
np.save('/home/dangnh36/datasets/competitions/leash_belka/processed/features/maccs/train.npy', np.array(arr))

In [ ]:
arr = np.memmap('/home/dangnh36/datasets/competitions/leash_belka/processed/features/maccs/test.mmap',
               dtype = np.uint8, shape = (878_022, 21))
arr.shape

In [ ]:
np.save('/home/dangnh36/datasets/competitions/leash_belka/processed/features/maccs/test.npy', np.array(arr))